# Men's Scrape Schedule

Get schedule of each team in a given year. This file needs to be ran for every relevant year (2012 to 2024).

### Web Scraping

Fair warning that this program unfortunately takes a very long time to run due to web scraping limits set by Sports Reference

In [1]:
import pandas as pd
import numpy as np
import time

season = 2025

df_active_teams = pd.read_html('https://www.sports-reference.com/cbb/schools/index.html')[0]
time.sleep(2)

df_active_teams = df_active_teams.loc[~df_active_teams['School'].isin([np.NaN, 'School']), :].reset_index(drop=True)

df_active_teams['From'] = pd.to_numeric(df_active_teams['From'], errors='coerce')
df_active_teams['To'] = pd.to_numeric(df_active_teams['To'], errors='coerce')

df_active_teams = df_active_teams.loc[(df_active_teams['To'] >= season) & (df_active_teams['From'] <= season), :].reset_index(drop=True)

if season == 2021:  # if 2021, remove ivy league because they cancelled their season in 2021
    df_active_teams = df_active_teams.loc[
        ~df_active_teams['School'].isin(['Princeton', 'Harvard', 'Yale', 'Pennsylvania', 'Brown', 'Columbia', 'Cornell', 'Dartmouth']), 
        :
    ].reset_index(drop=True)

df_active_teams

,Rk,School,"City, State",From,To,Yrs,G,W,L,W-L%,SRS,SOS,AP,CREG,CTRN,NCAA,FF,NC
0,1,Abilene Christian,"Abilene, Texas",1971,2025,15,449,239,210,.532,-7.57,-5.30,0,0,2,2,0,0
1,2,Air Force,"USAF Academy, Colorado",1958,2025,68,1869,796,1073,.426,-2.87,1.35,0,1,0,4,0,0
2,3,Akron,"Akron, Ohio",1902,2025,74,1744,1048,696,.601,0.09,-1.60,0,9,6,6,0,0
3,4,Alabama,"Tuscaloosa, Alabama",1913,2025,112,2922,1815,1106,.621,8.16,5.05,18,10,9,25,1,0
4,5,Alabama A&M,"Normal, Alabama",2000,2025,26,749,286,463,.382,-16.71,-11.01,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,489,Wright State,"Dayton, Ohio",1988,2025,38,1157,644,513,.557,-1.40,-2.58,0,4,4,4,0,0
360,490,Wyoming,"Laramie, Wyoming",1905,2025,120,2906,1622,1284,.558,2.70,2.76,4,21,3,16,1,1
361,491,Xavier,"Cincinnati, Ohio",1920,2025,104,2724,1628,1096,.598,6.19,4.05,13,18,9,29,0,0
362,492,Yale,"New Haven, Connecticut",1896,2025,129,3108,1583,1523,.510,-5.80,-4.42,1,16,3,7,0,0
363,493,Youngstown State,"Youngstown, Ohio",1948,2025,45,1321,548,773,.415,-7.86,-3.55,0,1,0,0,0,0

In [ ]:
from datetime import datetime

cutoff_dates = {
    2012: datetime(2012, 3, 14),
    2013: datetime(2013, 3, 20),
    2014: datetime(2014, 3, 19),
    2015: datetime(2015, 3, 18),
    2016: datetime(2016, 3, 16),
    2017: datetime(2017, 3, 15),
    2018: datetime(2018, 3, 14),
    2019: datetime(2019, 3, 20),
    2021: datetime(2021, 3, 18),
    2022: datetime(2022, 3, 16),
    2023: datetime(2023, 3, 15),
    2024: datetime(2024, 3, 20),
    2025: datetime(2025, 3, 19),
}

cutoff_dates[season]

datetime.datetime(2025, 3, 16, 0, 0)

Get school names used in Sports Reference URL

In [3]:
df_active_teams['URL School'] = df_active_teams['School']

# hard code some schools that cause issues
df_active_teams.loc[df_active_teams['School'] == 'Bowling Green', 'URL School'] = 'Bowling Green State'
df_active_teams.loc[df_active_teams['School'] == 'BYU', 'URL School'] = 'Brigham Young'
df_active_teams.loc[df_active_teams['School'] == 'Louisiana', 'URL School'] = 'Louisiana Lafayette'
df_active_teams.loc[df_active_teams['School'] == 'LSU', 'URL School'] = 'Louisiana State'
df_active_teams.loc[df_active_teams['School'] == 'Ole Miss', 'URL School'] = 'Mississippi'
df_active_teams.loc[df_active_teams['School'] == 'Pitt', 'URL School'] = 'Pittsburgh'
df_active_teams.loc[df_active_teams['School'] == 'SMU', 'URL School'] = 'Southern Methodist'
df_active_teams.loc[df_active_teams['School'] == 'UAB', 'URL School'] = 'Alabama Birmingham'
df_active_teams.loc[df_active_teams['School'] == 'UCF', 'URL School'] = 'Central Florida'
df_active_teams.loc[df_active_teams['School'] == 'USC', 'URL School'] = 'Southern California'
df_active_teams.loc[df_active_teams['School'] == 'UTEP', 'URL School'] = 'Texas El Paso'
df_active_teams.loc[df_active_teams['School'] == 'UTSA', 'URL School'] = 'Texas San Antonio'
df_active_teams.loc[df_active_teams['School'] == 'Sam Houston', 'URL School'] = 'Sam Houston State'
df_active_teams.loc[df_active_teams['School'] == 'Houston Christian', 'URL School'] = 'Houston Baptist'
df_active_teams.loc[df_active_teams['School'] == 'Kansas City', 'URL School'] = 'Missouri Kansas City'
df_active_teams.loc[df_active_teams['School'] == 'Little Rock', 'URL School'] = 'Arkansas Little Rock'
df_active_teams.loc[df_active_teams['School'] == 'NC State', 'URL School'] = 'North Carolina State'
df_active_teams.loc[df_active_teams['School'] == 'Omaha', 'URL School'] = 'Nebraska Omaha'
df_active_teams.loc[df_active_teams['School'] == 'Purdue Fort Wayne', 'URL School'] = 'IPFW'
df_active_teams.loc[df_active_teams['School'] == 'TCU', 'URL School'] = 'Texas Christian'
df_active_teams.loc[df_active_teams['School'] == 'Texas-Rio Grande Valley', 'URL School'] = 'Texas Pan American'
df_active_teams.loc[df_active_teams['School'] == 'The Citadel', 'URL School'] = 'Citadel'
df_active_teams.loc[df_active_teams['School'] == 'Utah Tech', 'URL School'] = 'Dixie State'
df_active_teams.loc[df_active_teams['School'] == 'St. Thomas', 'URL School'] = 'St. Thomas MN'
df_active_teams.loc[df_active_teams['School'] == 'UC Berkley', 'URL School'] = 'California'
df_active_teams.loc[df_active_teams['School'] == 'UT Arlington', 'URL School'] = 'Texas Arlington'
df_active_teams.loc[df_active_teams['School'] == 'FDU', 'URL School'] = 'Fairleigh Dickinson'
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'URL School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'URL School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'URL School'] = 'St. Francis (NY)'
df_active_teams.loc[df_active_teams['School'] == 'East Texas A&M', 'URL School'] = 'Texas A&M Commerce'
df_active_teams.loc[df_active_teams['School'] == 'IU Indy', 'URL School'] = 'IUPUI'

df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UC\s', 'California ', regex=True)
df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UNC\s', 'North Carolina ', regex=True)

In [4]:
urls = (
    'https://www.sports-reference.com/cbb/schools/' +
    df_active_teams['URL School'].str.replace(' ', '-', regex=False).str.replace('[)(&.\']', '', regex=True).str.replace('--', '-', regex=False).str.lower() +
    '/men/' + str(season) +
    '-gamelogs.html'
)

urls

0      https://www.sports-reference.com/cbb/schools/a...
1      https://www.sports-reference.com/cbb/schools/a...
2      https://www.sports-reference.com/cbb/schools/a...
3      https://www.sports-reference.com/cbb/schools/a...
4      https://www.sports-reference.com/cbb/schools/a...
                             ...
359    https://www.sports-reference.com/cbb/schools/w...
360    https://www.sports-reference.com/cbb/schools/w...
361    https://www.sports-reference.com/cbb/schools/x...
362    https://www.sports-reference.com/cbb/schools/y...
363    https://www.sports-reference.com/cbb/schools/y...
Name: URL School, Length: 364, dtype: object

In [5]:
from urllib.error import HTTPError
from tqdm.notebook import tqdm

problems = []

l = []
loop = tqdm(
    np.array((df_active_teams['School'], urls)).transpose(),  # get both school and url into loop iteration
    bar_format='{bar}{percentage:3.0f}%{r_bar}   {desc}'  # make the description not affect bar location
)
for (school, url) in loop:
  try:
    loop.set_description(f'{school}')
    # print(f'{i:03d}: {url}')
    df_team_season = pd.read_html(url)[-1]  # schools that were ranked have that info as the first table on the site
    time.sleep(2)

    df_team_season.columns = [i[1] if 'Unnamed' in i[0] else i[0] + ' ' + i[1] for i in df_team_season.columns]
    df_team_season.insert(2, 'Team', school)
    l.append(df_team_season)
  except ValueError as e:
    print(f'{url} | ValueError: {e}')
    time.sleep(2)
  except HTTPError as e:
    if e.code == 404:
      print(f'{url} | {e}')
      time.sleep(2)
    else:
      print(f'{url} | {e}')
      break

df = pd.concat(l, ignore_index=True)

df

            0%| 0/364 [00:00<?, ?it/s]

,G,Date,Team,Unnamed: 2_level_1,Opp,W/L,Tm,Opp,School FG,School FGA,...,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,1,2024-11-04,Abilene Christian,NaN,Howard Payne,W,107,74,42,73,...,19,25,.760,9,17,8,20,0,14,24
1,2,2024-11-09,Abilene Christian,NaN,Middle Tennessee,L,56,79,19,49,...,11,14,.786,7,30,13,14,4,13,21
2,3,2024-11-12,Abilene Christian,NaN,McMurry,W,101,55,41,74,...,18,23,.783,7,30,7,5,1,19,12
3,4,2024-11-16,Abilene Christian,NaN,Texas State,W,72,60,24,49,...,27,38,.711,3,21,6,8,3,15,20
4,5,2024-11-20,Abilene Christian,@,Kennesaw State,L,78,84,27,59,...,33,41,.805,7,30,13,3,3,19,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11940,28,2025-02-12,Youngstown State,NaN,Purdue Fort Wayne,W,93,71,30,60,...,9,11,.818,7,26,13,7,1,8,15
11941,29,2025-02-16,Youngstown State,@,Cleveland State,W,68,60,21,45,...,13,19,.684,13,26,10,5,2,11,19
11942,30,2025-02-21,Youngstown State,NaN,Milwaukee,L,74,84,25,51,...,21,25,.840,11,33,19,5,1,13,19
11943,31,2025-02-23,Youngstown State,NaN,Green Bay,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11944,32,2025-03-01,Youngstown State,@,Northern Kentucky,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11945 entries, 0 to 11944
Data columns (total 41 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   G                    11581 non-null  object
 1   Date                 11581 non-null  object
 2   Team                 11945 non-null  object
 3   Unnamed: 2_level_1   5735 non-null   object
 4   Opp                  11547 non-null  object
 5   W/L                  10150 non-null  object
 6   Tm                   10150 non-null  object
 7   Opp                  10150 non-null  object
 8   School FG            10512 non-null  object
 9   School FGA           10512 non-null  object
 10  School FG%           10512 non-null  object
 11  School 3P            10512 non-null  object
 12  School 3PA           10512 non-null  object
 13  School 3P%           10512 non-null  object
 14  School FT            10512 non-null  object
 15  School FTA           10512 non-null  object
 16  School FT%           10511 non-null  object
 17  School ORB           10512 non-null  object
 18  School TRB           10512 non-null  object
 19  School AST           10512 non-null  object
 20  School STL           10512 non-null  object
 21  School BLK           10512 non-null  object
 22  School TOV           10512 non-null  object
 23  School PF            10512 non-null  object
 24  Unnamed: 23_level_1  0 non-null      float64
 25  Opponent FG          10512 non-null  object
 26  Opponent FGA         10512 non-null  object
 27  Opponent FG%         10512 non-null  object
 28  Opponent 3P          10512 non-null  object
 29  Opponent 3PA         10512 non-null  object
 30  Opponent 3P%         10512 non-null  object
 31  Opponent FT          10512 non-null  object
 32  Opponent FTA         10512 non-null  object
 33  Opponent FT%         10510 non-null  object
 34  Opponent ORB         10512 non-null  object
 35  Opponent TRB         10512 non-null  object
 36  Opponent AST         10512 non-null  object
 37  Opponent STL         10512 non-null  object
 38  Opponent BLK         10512 non-null  object
 39  Opponent TOV         10512 non-null  object
 40  Opponent PF          10512 non-null  object
dtypes: float64(1), object(40)
memory usage: 3.7+ MB

### Data Setup

In [7]:
temp = df.copy()

In [8]:
df = temp.copy()

Fix column names and drop useless columns

In [9]:
df.columns = (
    ['G', 'Date', 'Team', 'Location', 'Opponent', 'Result', 'Team Score', 'Opponent Score'] +
    [c for c in df.columns[8:]]
)

# use "Team" as prefix instead of "School"
df.columns = df.columns.str.replace('School', 'Team', regex=False)

# drop columns that are completely null
df = df[[c for c in df.columns if df.loc[:, c].notna().any()]].copy()

# drop other irrelevant columns
df.drop(columns=['G'], inplace=True)

df

,Date,Team,Location,Opponent,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,...,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,2024-11-04,Abilene Christian,NaN,Howard Payne,W,107,74,42,73,.575,...,19,25,.760,9,17,8,20,0,14,24
1,2024-11-09,Abilene Christian,NaN,Middle Tennessee,L,56,79,19,49,.388,...,11,14,.786,7,30,13,14,4,13,21
2,2024-11-12,Abilene Christian,NaN,McMurry,W,101,55,41,74,.554,...,18,23,.783,7,30,7,5,1,19,12
3,2024-11-16,Abilene Christian,NaN,Texas State,W,72,60,24,49,.490,...,27,38,.711,3,21,6,8,3,15,20
4,2024-11-20,Abilene Christian,@,Kennesaw State,L,78,84,27,59,.458,...,33,41,.805,7,30,13,3,3,19,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11940,2025-02-12,Youngstown State,NaN,Purdue Fort Wayne,W,93,71,30,60,.500,...,9,11,.818,7,26,13,7,1,8,15
11941,2025-02-16,Youngstown State,@,Cleveland State,W,68,60,21,45,.467,...,13,19,.684,13,26,10,5,2,11,19
11942,2025-02-21,Youngstown State,NaN,Milwaukee,L,74,84,25,51,.490,...,21,25,.840,11,33,19,5,1,13,19
11943,2025-02-23,Youngstown State,NaN,Green Bay,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11944,2025-03-01,Youngstown State,@,Northern Kentucky,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Reformat result column because it contains information about overtime

In [10]:
# remove games that have not been played
df = df.loc[(df['Result'].notna()) & (df['Result'] != 'W/L'), :].reset_index(drop=True)

# get overtime info
df['Overtimes Amount'] = df['Result'].str.extract(r'(\d+)').astype('float16')
df.loc[df['Overtimes Amount'].isna(), 'Overtimes Amount'] = 0
df['Overtimes Amount'] = df['Overtimes Amount'].astype(int)

# binary overtime flag
df['Overtime'] = df['Overtimes Amount'].copy()
df.loc[df['Overtime'] > 1, 'Overtime'] = 1
df['Overtime'] = df['Overtime'].astype('int8')

# reformat result column
df['Result'] = df['Result'].str[:1].map({'W': 1, 'L': -1}).astype('int8')

df

,Date,Team,Location,Opponent,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,...,Opponent FT%,Opponent ORB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,2024-11-04,Abilene Christian,NaN,Howard Payne,1,107,74,42,73,.575,...,.760,9,17,8,20,0,14,24,0,0
1,2024-11-09,Abilene Christian,NaN,Middle Tennessee,-1,56,79,19,49,.388,...,.786,7,30,13,14,4,13,21,0,0
2,2024-11-12,Abilene Christian,NaN,McMurry,1,101,55,41,74,.554,...,.783,7,30,7,5,1,19,12,0,0
3,2024-11-16,Abilene Christian,NaN,Texas State,1,72,60,24,49,.490,...,.711,3,21,6,8,3,15,20,0,0
4,2024-11-20,Abilene Christian,@,Kennesaw State,-1,78,84,27,59,.458,...,.805,7,30,13,3,3,19,20,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9781,2025-02-06,Youngstown State,@,Oakland,1,84,75,29,66,.439,...,.600,10,34,14,7,2,17,17,0,0
9782,2025-02-08,Youngstown State,@,Detroit Mercy,1,87,72,27,58,.466,...,.789,12,33,12,5,1,13,16,0,0
9783,2025-02-12,Youngstown State,NaN,Purdue Fort Wayne,1,93,71,30,60,.500,...,.818,7,26,13,7,1,8,15,0,0
9784,2025-02-16,Youngstown State,@,Cleveland State,1,68,60,21,45,.467,...,.684,13,26,10,5,2,11,19,0,0
9785,2025-02-21,Youngstown State,NaN,Milwaukee,-1,74,84,25,51,.490,...,.840,11,33,19,5,1,13,19,0,0

Reformat location column for home/neutral/away

In [11]:
df['Location'] = df['Location'].map({np.NaN: 1, 'N': 0, '@': -1}).astype('int8')

df['Location']

0       1
1       1
2       1
3       1
4      -1
       ..
9781   -1
9782   -1
9783    1
9784   -1
9785    1
Name: Location, Length: 9786, dtype: int8

Other general fixes

In [12]:
# fix dates
df['Date'] = pd.to_datetime(df['Date'])

# only include games before NCAA tournament
df = df.loc[df['Date'] <= cutoff_dates[season], :].reset_index(drop=True)

# fix column types
df.loc[:, df.columns.str.contains('Team ', regex=False)] = df.loc[:, df.columns.str.contains('Team ', regex=False)].astype('float64')
df.loc[:, df.columns.str.contains('Opponent ', regex=False)] = df.loc[:, df.columns.str.contains('Opponent ', regex=False)].astype('float64')

df

,Date,Team,Location,Opponent,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,...,Opponent FT%,Opponent ORB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,2024-11-04,Abilene Christian,1,Howard Payne,1,107.0,74.0,42.0,73.0,0.575,...,0.76,9.0,17.0,8.0,20.0,0.0,14.0,24.0,0,0
1,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,56.0,79.0,19.0,49.0,0.388,...,0.786,7.0,30.0,13.0,14.0,4.0,13.0,21.0,0,0
2,2024-11-12,Abilene Christian,1,McMurry,1,101.0,55.0,41.0,74.0,0.554,...,0.783,7.0,30.0,7.0,5.0,1.0,19.0,12.0,0,0
3,2024-11-16,Abilene Christian,1,Texas State,1,72.0,60.0,24.0,49.0,0.49,...,0.711,3.0,21.0,6.0,8.0,3.0,15.0,20.0,0,0
4,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,78.0,84.0,27.0,59.0,0.458,...,0.805,7.0,30.0,13.0,3.0,3.0,19.0,20.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9781,2025-02-06,Youngstown State,-1,Oakland,1,84.0,75.0,29.0,66.0,0.439,...,0.6,10.0,34.0,14.0,7.0,2.0,17.0,17.0,0,0
9782,2025-02-08,Youngstown State,-1,Detroit Mercy,1,87.0,72.0,27.0,58.0,0.466,...,0.789,12.0,33.0,12.0,5.0,1.0,13.0,16.0,0,0
9783,2025-02-12,Youngstown State,1,Purdue Fort Wayne,1,93.0,71.0,30.0,60.0,0.5,...,0.818,7.0,26.0,13.0,7.0,1.0,8.0,15.0,0,0
9784,2025-02-16,Youngstown State,-1,Cleveland State,1,68.0,60.0,21.0,45.0,0.467,...,0.684,13.0,26.0,10.0,5.0,2.0,11.0,19.0,0,0
9785,2025-02-21,Youngstown State,1,Milwaukee,-1,74.0,84.0,25.0,51.0,0.49,...,0.84,11.0,33.0,19.0,5.0,1.0,13.0,19.0,0,0

Remap opponent names because the opponents sometimes have a different naming convention than the team names

In [13]:
# create new dataframe from opposite perspective    team <--> opponent
df_switch = df.copy()

df_switch.columns = df_switch.columns.str.replace(
    'Team', '_TEMP_', regex=False
).str.replace(
    'Opponent', 'Team', regex=False
).str.replace(
    '_TEMP_', 'Opponent', regex=False
)

df_switch[['Location', 'Result']] *= -1

# get fixed opponent names
df['Opponent'] = pd.merge(
    df, df_switch,
    how='left',
    on=(
        ['Date', 'Location', 'Result'] +
        list(df.loc[:, df.columns.str.contains('Team ')].columns) +
        list(df.loc[:, df.columns.str.contains('Opponent ')].columns)
    )
)['Opponent_y']

# Remove matchups that are not division 1
df = df.loc[df['Opponent'].notna(), :].reset_index(drop=True)

df

,Date,Team,Location,Opponent,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,...,Opponent FT%,Opponent ORB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,56.0,79.0,19.0,49.0,0.388,...,0.786,7.0,30.0,13.0,14.0,4.0,13.0,21.0,0,0
1,2024-11-16,Abilene Christian,1,Texas State,1,72.0,60.0,24.0,49.0,0.49,...,0.711,3.0,21.0,6.0,8.0,3.0,15.0,20.0,0,0
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,78.0,84.0,27.0,59.0,0.458,...,0.805,7.0,30.0,13.0,3.0,3.0,19.0,20.0,0,0
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,82.0,74.0,24.0,47.0,0.511,...,0.594,8.0,23.0,14.0,4.0,2.0,12.0,26.0,0,0
4,2024-11-26,Abilene Christian,-1,Montana State,-1,59.0,85.0,24.0,58.0,0.414,...,0.769,5.0,31.0,20.0,4.0,4.0,13.0,15.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9253,2025-02-06,Youngstown State,-1,Oakland,1,84.0,75.0,29.0,66.0,0.439,...,0.6,10.0,34.0,14.0,7.0,2.0,17.0,17.0,0,0
9254,2025-02-08,Youngstown State,-1,Detroit Mercy,1,87.0,72.0,27.0,58.0,0.466,...,0.789,12.0,33.0,12.0,5.0,1.0,13.0,16.0,0,0
9255,2025-02-12,Youngstown State,1,Purdue Fort Wayne,1,93.0,71.0,30.0,60.0,0.5,...,0.818,7.0,26.0,13.0,7.0,1.0,8.0,15.0,0,0
9256,2025-02-16,Youngstown State,-1,Cleveland State,1,68.0,60.0,21.0,45.0,0.467,...,0.684,13.0,26.0,10.0,5.0,2.0,11.0,19.0,0,0
9257,2025-02-21,Youngstown State,1,Milwaukee,-1,74.0,84.0,25.0,51.0,0.49,...,0.84,11.0,33.0,19.0,5.0,1.0,13.0,19.0,0,0

Set up adjusted Score Differential

In [14]:
blowout_threshold = 18  # adjusted score differential will only account up to this score difference

df['Score Differential'] = df['Team Score'] - df['Opponent Score']

df['Adjusted Score Differential'] = df['Score Differential'].abs()

df.loc[df['Adjusted Score Differential'] > blowout_threshold, 'Adjusted Score Differential'] = blowout_threshold

df['Adjusted Score Differential'] = df['Adjusted Score Differential']**(np.log(1.5)/np.log(blowout_threshold))

df

,Date,Team,Location,Opponent,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,...,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,56.0,79.0,19.0,49.0,0.388,...,30.0,13.0,14.0,4.0,13.0,21.0,0,0,-23.0,1.5
1,2024-11-16,Abilene Christian,1,Texas State,1,72.0,60.0,24.0,49.0,0.49,...,21.0,6.0,8.0,3.0,15.0,20.0,0,0,12.0,1.417062
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,78.0,84.0,27.0,59.0,0.458,...,30.0,13.0,3.0,3.0,19.0,20.0,0,0,-6.0,1.28576
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,82.0,74.0,24.0,47.0,0.511,...,23.0,14.0,4.0,2.0,12.0,26.0,0,0,8.0,1.33871
4,2024-11-26,Abilene Christian,-1,Montana State,-1,59.0,85.0,24.0,58.0,0.414,...,31.0,20.0,4.0,4.0,13.0,15.0,0,0,-26.0,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9253,2025-02-06,Youngstown State,-1,Oakland,1,84.0,75.0,29.0,66.0,0.439,...,34.0,14.0,7.0,2.0,17.0,17.0,0,0,9.0,1.361013
9254,2025-02-08,Youngstown State,-1,Detroit Mercy,1,87.0,72.0,27.0,58.0,0.466,...,33.0,12.0,5.0,1.0,13.0,16.0,0,0,15.0,1.462122
9255,2025-02-12,Youngstown State,1,Purdue Fort Wayne,1,93.0,71.0,30.0,60.0,0.5,...,26.0,13.0,7.0,1.0,8.0,15.0,0,0,22.0,1.5
9256,2025-02-16,Youngstown State,-1,Cleveland State,1,68.0,60.0,21.0,45.0,0.467,...,26.0,10.0,5.0,2.0,11.0,19.0,0,0,8.0,1.33871
9257,2025-02-21,Youngstown State,1,Milwaukee,-1,74.0,84.0,25.0,51.0,0.49,...,33.0,19.0,5.0,1.0,13.0,19.0,0,0,-10.0,1.381279

Get per possession stats

In [15]:
Y = 0.44

df['Possessions'] = (
    df['Team FGA'] - df['Team ORB'] + df['Team TOV'] + Y*df['Team FTA'] +
    df['Opponent FGA'] - df['Opponent ORB'] + df['Opponent TOV'] + Y*df['Opponent FTA']
)/2

df['Team PPP'] = df['Team Score'] / df['Possessions']
df['Opponent PPP'] = df['Opponent Score'] / df['Possessions']
df['Tempo'] = 40*df['Possessions'] / (40 + 5*df['Overtimes Amount'])

# some games are missing stats due to delay/finished recently
df = df.loc[df['Team PPP'].notna(), :].reset_index(drop=True)

df

,Date,Team,Location,Opponent,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,...,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,56.0,79.0,19.0,49.0,0.388,...,13.0,21.0,0,0,-23.0,1.5,71.08,0.787845,1.111424,71.08
1,2024-11-16,Abilene Christian,1,Texas State,1,72.0,60.0,24.0,49.0,0.49,...,15.0,20.0,0,0,12.0,1.417062,67.2,1.071429,0.892857,67.2
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,78.0,84.0,27.0,59.0,0.458,...,19.0,20.0,0,0,-6.0,1.28576,72.12,1.081531,1.164725,72.12
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,82.0,74.0,24.0,47.0,0.511,...,12.0,26.0,0,0,8.0,1.33871,66.84,1.22681,1.107121,66.84
4,2024-11-26,Abilene Christian,-1,Montana State,-1,59.0,85.0,24.0,58.0,0.414,...,13.0,15.0,0,0,-26.0,1.5,64.0,0.921875,1.328125,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9251,2025-02-06,Youngstown State,-1,Oakland,1,84.0,75.0,29.0,66.0,0.439,...,17.0,17.0,0,0,9.0,1.361013,76.64,1.096033,0.978601,76.64
9252,2025-02-08,Youngstown State,-1,Detroit Mercy,1,87.0,72.0,27.0,58.0,0.466,...,13.0,16.0,0,0,15.0,1.462122,65.58,1.326624,1.097896,65.58
9253,2025-02-12,Youngstown State,1,Purdue Fort Wayne,1,93.0,71.0,30.0,60.0,0.5,...,8.0,15.0,0,0,22.0,1.5,69.7,1.33429,1.018651,69.7
9254,2025-02-16,Youngstown State,-1,Cleveland State,1,68.0,60.0,21.0,45.0,0.467,...,11.0,19.0,0,0,8.0,1.33871,65.9,1.031866,0.91047,65.9
9255,2025-02-21,Youngstown State,1,Milwaukee,-1,74.0,84.0,25.0,51.0,0.49,...,13.0,19.0,0,0,-10.0,1.381279,69.4,1.066282,1.210375,69.4

### Save

In [ ]:
df.to_parquet(f'../data/unprocessed/mens_sports_reference/sports_reference_{season}.parquet', index=False)

'Done'

'Done'