# Get Men's Barttorvik Ratings

Get the Barttorvik ratings from previous seasons for features about previous team strength. Assumes all data has been copied from website (https://barttorvik.com/team-tables_each.php) to Excel, as specified in the steps below.

Steps before this file:

1. Copy from the website, only including games before tournament start date
2. Paste as text into Excel
3. Save into folder

cutoff_dates = {
    2012: datetime(2012, 3, 14),
    2013: datetime(2013, 3, 20),
    2014: datetime(2014, 3, 19),
    2015: datetime(2015, 3, 18),
    2016: datetime(2016, 3, 16),
    2017: datetime(2017, 3, 15),
    2018: datetime(2018, 3, 14),
    2019: datetime(2019, 3, 20),
    2021: datetime(2021, 3, 18),
    2022: datetime(2022, 3, 16),
    2023: datetime(2023, 3, 15),
    2024: datetime(2024, 3, 20),
    2025: datetime(2025, 3, 19),
}

In [1]:
SEASON = 2025
INCLUDE_CURRENT_SEASON = False

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

def load_data(season: int) -> pd.DataFrame:
    data = pd.read_excel(f'../data/unprocessed/mens_barttorvik/barttorvik_{season}.xlsx')
    data.columns = data.columns.str.upper()

    return data

df = pd.concat(
    [
        load_data(season)
        for season in range(2012, SEASON + INCLUDE_CURRENT_SEASON)
        if season != 2020  # cancelled
    ],
    ignore_index=True,
)

df.insert(0, 'Season', df.pop('YEAR'))

df

,Season,,TEAM,ADJ OE,ADJ DE,BARTHAG,RECORD,WINS,GAMES,EFG,EFG D.,FT RATE,FT RATE D,TOV%,TOV% D,O REB%,OP OREB%,RAW T,2P %,2P % D.,3P %,3P % D.,BLK %,BLKED %,AST %,OP AST %,3P RATE,3P RATE D,ADJ. T,AVG HGT.,EFF. HGT.,EXP.,PAKE,PASE,TALENT,UNNAMED: 35,FT%,OP. FT%,PPP OFF.,PPP DEF.,ELITE SOS,TEAM.1
0,2012,1,Kentucky,119.7,88.5,0.970,32–2,32,34,53.4,41.6,40.0,25.6,17.2,18.1,38.4,31.0,65.9,52.5,38.8,37.1,32.1,21.4,8.1,48.4,48.6,27.3,30.0,66.1,78.819,81.480,0.776,2.3,2.711,95.267,NaN,72.0,68.8,1.163,0.895,27.605,Kentucky
1,2012,2,Ohio St.,115.5,85.5,0.970,27–7,27,34,52.5,46.3,37.0,28.6,17.4,22.5,35.7,24.9,66.7,53.8,45.3,32.6,32.2,8.8,6.1,54.3,47.2,26.1,35.5,68.1,77.651,80.091,1.254,1.0,1.671,87.821,NaN,69.8,68.9,1.121,0.886,31.751,Ohio St.
2,2012,3,Kansas,114.7,88.1,0.954,27–6,27,33,54.0,43.9,41.1,34.3,19.6,20.7,34.9,28.6,67.5,54.1,40.0,35.8,34.7,15.1,8.2,58.6,52.4,30.5,32.2,67.9,78.482,81.633,2.178,2.3,2.671,72.255,NaN,69.6,72.1,1.108,0.914,30.956,Kansas
3,2012,4,Michigan St.,112.7,86.7,0.953,27–7,27,34,52.7,43.0,39.0,34.2,19.8,19.7,37.2,27.5,65.3,51.9,42.6,36.5,29.2,12.7,7.3,59.1,52.2,27.8,35.6,66.1,76.890,80.061,1.672,-0.6,-1.289,67.935,NaN,69.8,70.5,1.101,0.903,34.349,Michigan St.
4,2012,5,North Carolina,115.8,89.6,0.950,29–5,29,34,50.0,45.1,38.1,22.0,16.2,18.5,40.5,27.7,72.8,49.6,43.5,34.0,31.9,13.8,6.9,58.1,46.4,22.9,35.9,72.7,79.495,82.601,1.384,0.6,-0.289,91.131,NaN,68.2,67.3,1.126,0.919,27.923,North Carolina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4225,2024,358,Stonehill,90.5,113.7,0.068,3–27,3,30,46.7,52.7,22.6,29.4,19.5,16.6,22.5,31.0,69.4,47.9,51.7,30.1,35.9,7.2,13.9,51.7,60.8,47.0,46.2,69.1,76.638,79.889,1.711,0.0,0.000,0.200,NaN,69.7,73.9,0.907,1.108,12.832,Stonehill
4226,2024,359,Saint Francis,93.3,117.3,0.067,6–22,6,28,47.2,53.0,32.6,35.4,21.2,17.1,32.9,31.3,66.4,45.7,52.9,33.2,35.4,10.1,11.8,52.6,52.0,35.1,37.1,66.4,76.921,79.692,0.327,0.0,0.000,0.200,NaN,60.6,70.3,0.949,1.106,8.567,Saint Francis
4227,2024,360,IU Indy,92.7,116.9,0.065,3–26,3,29,46.5,58.2,33.2,33.4,21.3,18.5,30.0,35.5,68.6,49.5,59.0,24.7,38.0,6.0,7.7,42.4,55.3,24.3,37.5,68.3,76.583,79.492,2.044,0.0,0.000,4.750,NaN,72.3,73.5,0.939,1.183,10.790,IU Indy
4228,2024,361,Coppin St.,84.7,110.0,0.047,2–27,2,29,42.1,51.3,31.1,38.3,22.9,21.8,27.0,38.6,67.3,41.9,51.0,28.3,34.5,8.0,9.5,40.7,58.6,34.4,37.6,67.3,76.929,80.172,1.292,0.0,0.000,4.358,NaN,72.6,73.9,0.852,1.073,9.758,Coppin St.
4229,2024,362,Mississippi Valley St.,85.4,116.4,0.028,1–30,1,31,42.5,55.6,33.0,41.6,24.0,17.2,27.9,35.7,66.2,41.9,55.6,29.2,37.0,6.5,8.7,44.2,54.1,30.4,36.5,65.5,76.125,78.967,2.689,0.0,0.000,0.200,NaN,65.8,71.4,0.834,1.168,18.849,Mississippi Valley St.

Create new columns

In [3]:
df.insert(df.columns.get_loc('WINS'), 'WIN%', df['WINS']/(df['GAMES']))
df.insert(df.columns.get_loc('ADJ DE') + 1, 'ADJ EM', df['ADJ OE'] - df['ADJ DE'])

df

,Season,,TEAM,ADJ OE,ADJ DE,ADJ EM,BARTHAG,RECORD,WIN%,WINS,GAMES,EFG,EFG D.,FT RATE,FT RATE D,TOV%,TOV% D,O REB%,OP OREB%,RAW T,2P %,2P % D.,3P %,3P % D.,BLK %,BLKED %,AST %,OP AST %,3P RATE,3P RATE D,ADJ. T,AVG HGT.,EFF. HGT.,EXP.,PAKE,PASE,TALENT,UNNAMED: 35,FT%,OP. FT%,PPP OFF.,PPP DEF.,ELITE SOS,TEAM.1
0,2012,1,Kentucky,119.7,88.5,31.2,0.970,32–2,0.941176,32,34,53.4,41.6,40.0,25.6,17.2,18.1,38.4,31.0,65.9,52.5,38.8,37.1,32.1,21.4,8.1,48.4,48.6,27.3,30.0,66.1,78.819,81.480,0.776,2.3,2.711,95.267,NaN,72.0,68.8,1.163,0.895,27.605,Kentucky
1,2012,2,Ohio St.,115.5,85.5,30.0,0.970,27–7,0.794118,27,34,52.5,46.3,37.0,28.6,17.4,22.5,35.7,24.9,66.7,53.8,45.3,32.6,32.2,8.8,6.1,54.3,47.2,26.1,35.5,68.1,77.651,80.091,1.254,1.0,1.671,87.821,NaN,69.8,68.9,1.121,0.886,31.751,Ohio St.
2,2012,3,Kansas,114.7,88.1,26.6,0.954,27–6,0.818182,27,33,54.0,43.9,41.1,34.3,19.6,20.7,34.9,28.6,67.5,54.1,40.0,35.8,34.7,15.1,8.2,58.6,52.4,30.5,32.2,67.9,78.482,81.633,2.178,2.3,2.671,72.255,NaN,69.6,72.1,1.108,0.914,30.956,Kansas
3,2012,4,Michigan St.,112.7,86.7,26.0,0.953,27–7,0.794118,27,34,52.7,43.0,39.0,34.2,19.8,19.7,37.2,27.5,65.3,51.9,42.6,36.5,29.2,12.7,7.3,59.1,52.2,27.8,35.6,66.1,76.890,80.061,1.672,-0.6,-1.289,67.935,NaN,69.8,70.5,1.101,0.903,34.349,Michigan St.
4,2012,5,North Carolina,115.8,89.6,26.2,0.950,29–5,0.852941,29,34,50.0,45.1,38.1,22.0,16.2,18.5,40.5,27.7,72.8,49.6,43.5,34.0,31.9,13.8,6.9,58.1,46.4,22.9,35.9,72.7,79.495,82.601,1.384,0.6,-0.289,91.131,NaN,68.2,67.3,1.126,0.919,27.923,North Carolina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4225,2024,358,Stonehill,90.5,113.7,-23.2,0.068,3–27,0.100000,3,30,46.7,52.7,22.6,29.4,19.5,16.6,22.5,31.0,69.4,47.9,51.7,30.1,35.9,7.2,13.9,51.7,60.8,47.0,46.2,69.1,76.638,79.889,1.711,0.0,0.000,0.200,NaN,69.7,73.9,0.907,1.108,12.832,Stonehill
4226,2024,359,Saint Francis,93.3,117.3,-24.0,0.067,6–22,0.214286,6,28,47.2,53.0,32.6,35.4,21.2,17.1,32.9,31.3,66.4,45.7,52.9,33.2,35.4,10.1,11.8,52.6,52.0,35.1,37.1,66.4,76.921,79.692,0.327,0.0,0.000,0.200,NaN,60.6,70.3,0.949,1.106,8.567,Saint Francis
4227,2024,360,IU Indy,92.7,116.9,-24.2,0.065,3–26,0.103448,3,29,46.5,58.2,33.2,33.4,21.3,18.5,30.0,35.5,68.6,49.5,59.0,24.7,38.0,6.0,7.7,42.4,55.3,24.3,37.5,68.3,76.583,79.492,2.044,0.0,0.000,4.750,NaN,72.3,73.5,0.939,1.183,10.790,IU Indy
4228,2024,361,Coppin St.,84.7,110.0,-25.3,0.047,2–27,0.068966,2,29,42.1,51.3,31.1,38.3,22.9,21.8,27.0,38.6,67.3,41.9,51.0,28.3,34.5,8.0,9.5,40.7,58.6,34.4,37.6,67.3,76.929,80.172,1.292,0.0,0.000,4.358,NaN,72.6,73.9,0.852,1.073,9.758,Coppin St.
4229,2024,362,Mississippi Valley St.,85.4,116.4,-31.0,0.028,1–30,0.032258,1,31,42.5,55.6,33.0,41.6,24.0,17.2,27.9,35.7,66.2,41.9,55.6,29.2,37.0,6.5,8.7,44.2,54.1,30.4,36.5,65.5,76.125,78.967,2.689,0.0,0.000,0.200,NaN,65.8,71.4,0.834,1.168,18.849,Mississippi Valley St.

Remove some columns

In [4]:
df = df.loc[
    : , 
    ~(
        (
            df.columns.isin([
                ' ', 
                'TEAM.1', 
                'RECORD', 
                'AVG HGT.', 
                'OP. FT%', 
                'PPP OFF.', 
                'PPP DEF.',
                '2P %',
                '2P % D',
                '3P %',
                '3P % D',
                'PAKE',  # DO NOT USE PAKE OR PASE; they are calculated post tourney despite being in earlier data
                'PASE',  # DO NOT USE PAKE OR PASE; they are calculated post tourney despite being in earlier data
                'WINS',
                'GAMES',
            ])
        ) | 
        (
            df.columns.str.contains('UNNAMED')
        )
    )
]

df

,Season,TEAM,ADJ OE,ADJ DE,ADJ EM,BARTHAG,WIN%,EFG,EFG D.,FT RATE,FT RATE D,TOV%,TOV% D,O REB%,OP OREB%,RAW T,2P % D.,3P % D.,BLK %,BLKED %,AST %,OP AST %,3P RATE,3P RATE D,ADJ. T,EFF. HGT.,EXP.,TALENT,FT%,ELITE SOS
0,2012,Kentucky,119.7,88.5,31.2,0.970,0.941176,53.4,41.6,40.0,25.6,17.2,18.1,38.4,31.0,65.9,38.8,32.1,21.4,8.1,48.4,48.6,27.3,30.0,66.1,81.480,0.776,95.267,72.0,27.605
1,2012,Ohio St.,115.5,85.5,30.0,0.970,0.794118,52.5,46.3,37.0,28.6,17.4,22.5,35.7,24.9,66.7,45.3,32.2,8.8,6.1,54.3,47.2,26.1,35.5,68.1,80.091,1.254,87.821,69.8,31.751
2,2012,Kansas,114.7,88.1,26.6,0.954,0.818182,54.0,43.9,41.1,34.3,19.6,20.7,34.9,28.6,67.5,40.0,34.7,15.1,8.2,58.6,52.4,30.5,32.2,67.9,81.633,2.178,72.255,69.6,30.956
3,2012,Michigan St.,112.7,86.7,26.0,0.953,0.794118,52.7,43.0,39.0,34.2,19.8,19.7,37.2,27.5,65.3,42.6,29.2,12.7,7.3,59.1,52.2,27.8,35.6,66.1,80.061,1.672,67.935,69.8,34.349
4,2012,North Carolina,115.8,89.6,26.2,0.950,0.852941,50.0,45.1,38.1,22.0,16.2,18.5,40.5,27.7,72.8,43.5,31.9,13.8,6.9,58.1,46.4,22.9,35.9,72.7,82.601,1.384,91.131,68.2,27.923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4225,2024,Stonehill,90.5,113.7,-23.2,0.068,0.100000,46.7,52.7,22.6,29.4,19.5,16.6,22.5,31.0,69.4,51.7,35.9,7.2,13.9,51.7,60.8,47.0,46.2,69.1,79.889,1.711,0.200,69.7,12.832
4226,2024,Saint Francis,93.3,117.3,-24.0,0.067,0.214286,47.2,53.0,32.6,35.4,21.2,17.1,32.9,31.3,66.4,52.9,35.4,10.1,11.8,52.6,52.0,35.1,37.1,66.4,79.692,0.327,0.200,60.6,8.567
4227,2024,IU Indy,92.7,116.9,-24.2,0.065,0.103448,46.5,58.2,33.2,33.4,21.3,18.5,30.0,35.5,68.6,59.0,38.0,6.0,7.7,42.4,55.3,24.3,37.5,68.3,79.492,2.044,4.750,72.3,10.790
4228,2024,Coppin St.,84.7,110.0,-25.3,0.047,0.068966,42.1,51.3,31.1,38.3,22.9,21.8,27.0,38.6,67.3,51.0,34.5,8.0,9.5,40.7,58.6,34.4,37.6,67.3,80.172,1.292,4.358,72.6,9.758
4229,2024,Mississippi Valley St.,85.4,116.4,-31.0,0.028,0.032258,42.5,55.6,33.0,41.6,24.0,17.2,27.9,35.7,66.2,55.6,37.0,6.5,8.7,44.2,54.1,30.4,36.5,65.5,78.967,2.689,0.200,65.8,18.849

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4230 entries, 0 to 4229
Data columns (total 30 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Season     4230 non-null   int64
 1   TEAM       4230 non-null   object
 2   ADJ OE     4230 non-null   float64
 3   ADJ DE     4230 non-null   float64
 4   ADJ EM     4230 non-null   float64
 5   BARTHAG    4230 non-null   float64
 6   WIN%       4230 non-null   float64
 7   EFG        4230 non-null   float64
 8   EFG D.     4230 non-null   float64
 9   FT RATE    4230 non-null   float64
 10  FT RATE D  4230 non-null   float64
 11  TOV%       4230 non-null   float64
 12  TOV% D     4230 non-null   float64
 13  O REB%     4230 non-null   float64
 14  OP OREB%   4230 non-null   float64
 15  RAW T      4230 non-null   float64
 16  2P % D.    4230 non-null   float64
 17  3P % D.    4230 non-null   float64
 18  BLK %      4230 non-null   float64
 19  BLKED %    4230 non-null   float64
 20  AST %      4230 non-null   float64
 21  OP AST %   4230 non-null   float64
 22  3P RATE    4230 non-null   float64
 23  3P RATE D  4230 non-null   float64
 24  ADJ. T     4230 non-null   float64
 25  EFF. HGT.  4230 non-null   float64
 26  EXP.       4230 non-null   float64
 27  TALENT     4230 non-null   float64
 28  FT%        4230 non-null   float64
 29  ELITE SOS  4230 non-null   float64
dtypes: float64(28), int64(1), object(1)
memory usage: 991.5+ KB

In [6]:
df.to_parquet(f'../data/preprocessed/mens_barttorvik/barttorvik.parquet')

'Done'

'Done'