# Get Men's Barttorvik Ratings

Get the Barttorvik ratings from previous seasons for features about previous team strength. Assumes all data has been copied from website (https://barttorvik.com/ncaaw/trank.php?year=...) to Excel, as specified in the steps below.

Steps before this file:

1. Copy from the website, only including games before tournament start date, excluding the initial row with D1 averages
2. Make sure the REC column in excel is text only before pasting (otherwise it tries to convert the records into a date)
3. Paste into excel with "Match Destination Formatting"
4. Save

In [1]:
SEASON = 2025
INCLUDE_CURRENT_SEASON = False

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

def read_barttorvik(season):
    d = pd.read_excel(f'../data/unprocessed/womens_barttorvik/barttorvik_{season}.xlsx')
    d.columns = d.columns.str.upper()
    d.insert(0, 'Season', season)
    return d


df = pd.concat(
    [
        read_barttorvik(season)
        for season in range(2021, SEASON + INCLUDE_CURRENT_SEASON)  # women's barttorvik starts in 2021
        if season != 2020  # cancelled
    ],
    ignore_index=True,
)

df.insert(0, 'Season', df.pop('Season'))

df

,Season,RK,TEAM,CONF,G,REC,ADJOE,ADJDE,BARTHAG,EFG%,EFGD%,TOR,TORD,ORB,DRB,FTR,FTRD,2P%,2P%D,3P%,3P%D,3PR,3PRD,ADJ T.,WAB
0,2021,1,Stanford,P12,29,27–2,123.1,70.6,0.9983,53.9,37.2,18.5,22.4,37.8,26,20.5,25.7,52.2,36.1,37.9,26.3,36.7,34.7,70.3,12.3
1,2021,NaN,"1 seed, CHAMPS",NaN,NaN,19–2,3,3,1,8,2,31,156,27,23,327,105,14,2,6,19,90,221,156,1
2,2021,2,Connecticut,BE,27,26–1,116.7,69.9,0.9972,57,37.8,19.8,25.4,37.1,24.6,24.9,16,59.1,36.8,34.7,26.3,30.3,37,71,7.2
3,2021,NaN,"1 seed, Final Four",NaN,NaN,18–0,5,1,2,2,5,62,62,34,9,257,1,2,5,50,19,223,284,122,9
4,2021,3,Baylor,B12,29,27–2,114.4,70.1,0.9964,51.4,36.1,21.8,23.8,46.2,23.1,30,27.8,51.6,34.2,33.5,26.7,16.3,32.7,73.4,10.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2887,2024,NaN,NaN,NaN,NaN,4–12,359,351,358,322,292,353,44,221,343,96,301,311,274,323,280,299,317,118,330
2888,2024,359,South Carolina St.,MEAC,30,2–28,70.5,107.1,0.0081,38.2,46.6,32.6,21.7,29.5,39.9,36,27.1,38.4,45.1,25.1,32.9,23.4,36.2,68.1,-25.8
2889,2024,NaN,NaN,NaN,NaN,1–13,360,349,359,353,221,360,208,223,358,19,159,346,178,342,279,336,296,251,360
2890,2024,360,Saint Francis,NEC,30,5–25,73.3,114.2,0.006,38.8,48,25,19.1,29.1,35,23.1,29.5,39,47.4,25.7,32.8,29.8,30.5,67.9,-23.2
2891,2024,NaN,NaN,NaN,NaN,4–12,355,360,360,347,280,291,320,227,302,309,221,341,266,336,275,233,111,263,352

In [3]:
df['RK'] = pd.to_numeric(df['RK'], errors='coerce')

df = df.loc[df['RK'].notna(), :].reset_index(drop=True)

df['RK'] = df['RK'].astype(int)

df

,Season,RK,TEAM,CONF,G,REC,ADJOE,ADJDE,BARTHAG,EFG%,EFGD%,TOR,TORD,ORB,DRB,FTR,FTRD,2P%,2P%D,3P%,3P%D,3PR,3PRD,ADJ T.,WAB
0,2021,1,Stanford,P12,29,27–2,123.1,70.6,0.9983,53.9,37.2,18.5,22.4,37.8,26,20.5,25.7,52.2,36.1,37.9,26.3,36.7,34.7,70.3,12.3
1,2021,2,Connecticut,BE,27,26–1,116.7,69.9,0.9972,57,37.8,19.8,25.4,37.1,24.6,24.9,16,59.1,36.8,34.7,26.3,30.3,37,71,7.2
2,2021,3,Baylor,B12,29,27–2,114.4,70.1,0.9964,51.4,36.1,21.8,23.8,46.2,23.1,30,27.8,51.6,34.2,33.5,26.7,16.3,32.7,73.4,10.3
3,2021,4,Maryland,B10,28,26–2,129.7,83.2,0.9939,56,46.3,16.3,22.4,41.4,31.8,29.5,24.8,53.8,44.6,40.6,32.9,30,34,72.8,10.1
4,2021,5,South Carolina,SEC,28,24–4,111.6,72.3,0.9933,46.9,39.5,19.5,19.9,42.8,24.8,33.3,21,46.6,39.5,32.1,26.5,20.1,23.7,71.8,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1415,2024,356,Chicago St.,Ind,26,0–26,76.3,111.4,0.0126,38,50.7,27.7,19.6,28.8,40.1,26.9,34.7,38.8,52.1,22.9,31.8,18,31.2,75.9,-23.3
1416,2024,357,Stonehill,NEC,30,4–26,72.9,108.2,0.0105,39.1,47.9,27.8,20.2,29.6,36.4,22.6,23.6,37.8,48.8,27.6,30.4,35.9,28.4,69.5,-24.7
1417,2024,358,Wagner,NEC,27,6–21,71.3,107.8,0.0086,40.3,48.3,28.6,26,29.6,37.3,30.5,33.2,40.4,47.6,26.6,33,26.5,37.4,70.6,-20.1
1418,2024,359,South Carolina St.,MEAC,30,2–28,70.5,107.1,0.0081,38.2,46.6,32.6,21.7,29.5,39.9,36,27.1,38.4,45.1,25.1,32.9,23.4,36.2,68.1,-25.8
1419,2024,360,Saint Francis,NEC,30,5–25,73.3,114.2,0.006,38.8,48,25,19.1,29.1,35,23.1,29.5,39,47.4,25.7,32.8,29.8,30.5,67.9,-23.2

In [4]:
df['REC'] = df['REC'].str.replace('–', '-', regex=False)  # fix hyphen vs dash issues in REC column

df.insert(df.columns.get_loc('REC'), 'WINS', [i[0] for i in df['REC'].str.split('-', regex=False).to_list()])
df.insert(df.columns.get_loc('REC'), 'LOSSES', [i[1] for i in df['REC'].str.split('-', regex=False).to_list()])

df.loc[
    :, 
    ~df.columns.isin(['TEAM', 'CONF', 'REC', 'SEASON', 'RK', 'G', 'WINS', 'LOSSES'])
] = df.loc[
    :, 
    ~df.columns.isin(['TEAM', 'CONF', 'REC', 'SEASON', 'RK', 'G', 'WINS', 'LOSSES'])
].astype(float)

df[['Season', 'RK', 'G', 'WINS', 'LOSSES']] = df[['Season', 'RK', 'G', 'WINS', 'LOSSES']].astype(int)

df.insert(df.columns.get_loc('REC'), 'WIN%', df['WINS']/(df['WINS'] + df['LOSSES']))

del df['REC']

df.insert(df.columns.get_loc('ADJDE') + 1, 'ADJEM', df['ADJOE'] - df['ADJDE'])
# df.insert(df.columns.get_loc('EFGD%') + 1, 'EFG%M', df['EFG%'] - df['EFGD%'])
# df.insert(df.columns.get_loc('TORD') + 1, 'TORM', df['TOR'] - df['TORD'])
# df.insert(df.columns.get_loc('DRB') + 1, 'RBM', df['ORB'] - df['DRB'])
# df.insert(df.columns.get_loc('FTRD') + 1, 'FTRM', df['FTR'] - df['FTRD'])

df

,Season,RK,TEAM,CONF,G,WINS,LOSSES,WIN%,ADJOE,ADJDE,ADJEM,BARTHAG,EFG%,EFGD%,TOR,TORD,ORB,DRB,FTR,FTRD,2P%,2P%D,3P%,3P%D,3PR,3PRD,ADJ T.,WAB
0,2021,1,Stanford,P12,29,27,2,0.931034,123.1,70.6,52.5,0.9983,53.9,37.2,18.5,22.4,37.8,26.0,20.5,25.7,52.2,36.1,37.9,26.3,36.7,34.7,70.3,12.3
1,2021,2,Connecticut,BE,27,26,1,0.962963,116.7,69.9,46.8,0.9972,57.0,37.8,19.8,25.4,37.1,24.6,24.9,16.0,59.1,36.8,34.7,26.3,30.3,37.0,71.0,7.2
2,2021,3,Baylor,B12,29,27,2,0.931034,114.4,70.1,44.3,0.9964,51.4,36.1,21.8,23.8,46.2,23.1,30.0,27.8,51.6,34.2,33.5,26.7,16.3,32.7,73.4,10.3
3,2021,4,Maryland,B10,28,26,2,0.928571,129.7,83.2,46.5,0.9939,56.0,46.3,16.3,22.4,41.4,31.8,29.5,24.8,53.8,44.6,40.6,32.9,30.0,34.0,72.8,10.1
4,2021,5,South Carolina,SEC,28,24,4,0.857143,111.6,72.3,39.3,0.9933,46.9,39.5,19.5,19.9,42.8,24.8,33.3,21.0,46.6,39.5,32.1,26.5,20.1,23.7,71.8,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1415,2024,356,Chicago St.,Ind,26,0,26,0.000000,76.3,111.4,-35.1,0.0126,38.0,50.7,27.7,19.6,28.8,40.1,26.9,34.7,38.8,52.1,22.9,31.8,18.0,31.2,75.9,-23.3
1416,2024,357,Stonehill,NEC,30,4,26,0.133333,72.9,108.2,-35.3,0.0105,39.1,47.9,27.8,20.2,29.6,36.4,22.6,23.6,37.8,48.8,27.6,30.4,35.9,28.4,69.5,-24.7
1417,2024,358,Wagner,NEC,27,6,21,0.222222,71.3,107.8,-36.5,0.0086,40.3,48.3,28.6,26.0,29.6,37.3,30.5,33.2,40.4,47.6,26.6,33.0,26.5,37.4,70.6,-20.1
1418,2024,359,South Carolina St.,MEAC,30,2,28,0.066667,70.5,107.1,-36.6,0.0081,38.2,46.6,32.6,21.7,29.5,39.9,36.0,27.1,38.4,45.1,25.1,32.9,23.4,36.2,68.1,-25.8
1419,2024,360,Saint Francis,NEC,30,5,25,0.166667,73.3,114.2,-40.9,0.006,38.8,48.0,25.0,19.1,29.1,35.0,23.1,29.5,39.0,47.4,25.7,32.8,29.8,30.5,67.9,-23.2

In [5]:
df.drop(
    columns=[
        'RK',
        'CONF',
        'G',
        'WINS',
        'LOSSES',
        '2P%',
        '2P%D',
        '3P%',
        '3P%D',
        'ORB',
        'DRB',
        '3PR',
        '3PRD',
        'EFG%',
        'EFGD%',
        'TOR',
        'TORD',
        'FTR',
        'FTRD',
    ],
    inplace=True,
)

df

,Season,TEAM,WIN%,ADJOE,ADJDE,ADJEM,BARTHAG,ADJ T.,WAB
0,2021,Stanford,0.931034,123.1,70.6,52.5,0.9983,70.3,12.3
1,2021,Connecticut,0.962963,116.7,69.9,46.8,0.9972,71.0,7.2
2,2021,Baylor,0.931034,114.4,70.1,44.3,0.9964,73.4,10.3
3,2021,Maryland,0.928571,129.7,83.2,46.5,0.9939,72.8,10.1
4,2021,South Carolina,0.857143,111.6,72.3,39.3,0.9933,71.8,10.0
...,...,...,...,...,...,...,...,...,...
1415,2024,Chicago St.,0.000000,76.3,111.4,-35.1,0.0126,75.9,-23.3
1416,2024,Stonehill,0.133333,72.9,108.2,-35.3,0.0105,69.5,-24.7
1417,2024,Wagner,0.222222,71.3,107.8,-36.5,0.0086,70.6,-20.1
1418,2024,South Carolina St.,0.066667,70.5,107.1,-36.6,0.0081,68.1,-25.8
1419,2024,Saint Francis,0.166667,73.3,114.2,-40.9,0.006,67.9,-23.2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1420 entries, 0 to 1419
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Season   1420 non-null   int32
 1   TEAM     1420 non-null   object
 2   WIN%     1420 non-null   float64
 3   ADJOE    1420 non-null   object
 4   ADJDE    1420 non-null   object
 5   ADJEM    1420 non-null   object
 6   BARTHAG  1420 non-null   object
 7   ADJ T.   1420 non-null   object
 8   WAB      1420 non-null   object
dtypes: float64(1), int32(1), object(7)
memory usage: 94.4+ KB

In [7]:
df.to_parquet(f'../data/preprocessed/womens_barttorvik/barttorvik.parquet')

'Done'

'Done'