# Openskill Ratings

Calculate ratings using openskill algorithm for a given season. This file needs to be ran for every relevant season (starting in 2012).

In [1]:
SEASON = 2025

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df = pd.read_parquet(fr'..\data\unprocessed\mens_sports_reference\full_season_sports_reference_{SEASON}.parquet')

df = df.loc[df['NCAA Tournament'] == 0, :].reset_index(drop=True)  # only include games before NCAA Tournament

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,Abilene Christian,2024-11-09,0,1,Middle Tennessee,REG (Non-Conf),-1,56,79,19,49,0.388,2,14,0.143,17,35,0.486,0.408,16,25,0.640,9,20,29,9,8,5,19,15,31,60,0.517,6,17,0.353,25,43,0.581,0.567,11,14,0.786,7,23,30,13,14,4,13,21,0,0,-23,1.500000,71.08,0.787845,1.111424,71.08
1,Abilene Christian,2024-11-16,0,1,Texas State,REG (Non-Conf),1,72,60,24,49,0.490,8,13,0.615,16,36,0.444,0.571,16,22,0.727,9,23,32,14,11,4,19,32,15,37,0.405,3,8,0.375,12,29,0.414,0.446,27,38,0.711,3,18,21,6,8,3,15,20,0,0,12,1.417062,67.20,1.071429,0.892857,67.20
2,Abilene Christian,2024-11-20,0,-1,Kennesaw State,REG (Non-Conf),-1,78,84,27,59,0.458,5,15,0.333,22,44,0.500,0.500,19,30,0.633,6,14,20,16,13,2,7,25,22,41,0.537,7,16,0.438,15,25,0.600,0.622,33,41,0.805,7,23,30,13,3,3,19,20,0,0,-6,1.285760,72.12,1.081531,1.164725,72.12
3,Abilene Christian,2024-11-25,0,0,Southern Mississippi,REG (Non-Conf),1,82,74,24,47,0.511,3,9,0.333,21,38,0.553,0.543,31,40,0.775,10,21,31,12,8,2,12,24,23,49,0.469,9,16,0.563,14,33,0.424,0.561,19,32,0.594,8,15,23,14,4,2,12,26,0,0,8,1.338710,66.84,1.226810,1.107121,66.84
4,Abilene Christian,2024-11-26,0,-1,Montana State,REG (Non-Conf),-1,59,85,24,58,0.414,3,18,0.167,21,40,0.525,0.440,8,12,0.667,6,15,21,11,6,2,7,12,29,50,0.580,17,26,0.654,12,24,0.500,0.750,10,13,0.769,5,26,31,20,4,4,13,15,0,0,-26,1.500000,64.00,0.921875,1.328125,64.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11277,Youngstown State,2025-02-23,0,1,Green Bay,REG (Conf),1,81,77,27,55,0.491,6,18,0.333,21,37,0.568,0.545,21,31,0.677,9,25,34,10,5,5,16,19,27,59,0.458,9,29,0.310,18,30,0.600,0.534,14,21,0.667,10,21,31,19,9,1,12,23,0,0,4,1.214668,72.94,1.110502,1.055662,72.94
11278,Youngstown State,2025-03-01,0,-1,Northern Kentucky,REG (Conf),-1,79,88,26,57,0.456,14,29,0.483,12,28,0.429,0.579,13,17,0.765,7,16,23,18,5,1,10,18,30,58,0.517,9,24,0.375,21,34,0.618,0.595,19,23,0.826,8,24,32,15,3,4,8,16,0,0,-9,1.361013,67.80,1.165192,1.297935,67.80
11279,Youngstown State,2025-03-06,0,1,Purdue Fort Wayne,CTOURN,1,72,67,21,58,0.362,5,28,0.179,16,30,0.533,0.405,25,31,0.806,10,34,44,10,6,5,17,20,23,62,0.371,8,27,0.296,15,35,0.429,0.435,13,20,0.650,6,23,29,11,9,3,13,23,0,0,5,1.253292,78.22,0.920481,0.856558,78.22
11280,Youngstown State,2025-03-10,0,0,Cleveland State,CTOURN,1,56,54,18,50,0.360,8,25,0.320,10,25,0.400,0.440,12,23,0.522,12,20,32,11,10,4,11,12,19,46,0.413,8,12,0.667,11,34,0.324,0.500,8,12,0.667,6,20,26,12,7,5,15,19,0,0,2,1.102120,59.70,0.938023,0.904523,59.70
11281,Youngstown State,2025-03-11,0,0,Robert Morris,CTOURN,-1,78,89,27,63,0.429,11,29,0.379,16,34,0.471,0.516,13,17,0.765,7,25,32,17,5,7,5,21,29,62,0.468,11,22,0.500,18,40,0.450,0.556,20,28,0.714,14,26,40,23,2,4,8,16,0,0,-11,1.399871,68.40,1.140351,1.301170,68.40

Filter to just wins because I don't need duplicate perspectives

In [3]:
df = df.loc[
    df['Result'] == 1, 
    ['Date', 'Team', 'Location', 'Opponent', 'Result', 'Adjusted Score Differential']
].reset_index(drop=True)

df.sort_values(['Date'], inplace=True, ignore_index=True)

df

,Date,Team,Location,Opponent,Result,Adjusted Score Differential
0,2024-11-04,UCLA,1,Rider,1,1.500000
1,2024-11-04,Massachusetts,1,New Hampshire,1,1.500000
2,2024-11-04,Florida,0,South Florida,1,1.462122
3,2024-11-04,Tennessee,1,Gardner-Webb,1,1.475419
4,2024-11-04,Western Illinois,-1,San Jose State,1,1.214668
...,...,...,...,...,...,...
5636,2025-03-16,Florida,0,Tennessee,1,1.361013
5637,2025-03-16,Yale,0,Cornell,1,1.285760
5638,2025-03-16,Michigan,0,Wisconsin,1,1.285760
5639,2025-03-16,Memphis,0,UAB,1,1.417062
5640,2025-03-16,Virginia Commonwealth,0,George Mason,1,1.253292

In [4]:
def rescale_weights(arr, minimum, maximum):
    """
    Rescale the weights array to match desired weights.
    Assumes the data is already transformed where a 1 point win is 1.00, a blowout is 1.50, and a tie is 0.50.
    Ties will be weighted as half the minimum.
    """

    arr_scaled = ((arr - 1.00) / 0.50) * (maximum - minimum) + minimum
    arr_scaled[arr == 0.50] = minimum / 2
    return arr_scaled

In [5]:
from typing import Tuple
from openskill.models import BradleyTerryFull
import numpy as np

def get_season_ratings(X_train_weights: np.array, sigma: float, hfa_mu: float) -> Tuple[BradleyTerryFull, dict]:
    """
    Run the algorithm over the course of a season.

    Args:
        X_train_weights (np.array): Numpy array where each row is a game and columns are Winner, Loser, Location, Weight.
        sigma (float): The starting variance for each team rating.
        hfa_mu (float): The mu of home field advantage.

    Returns:
        Tuple[BradleyTerryFull, dict]: The environment object and dictionary of team ratings.
    """
    # initialize
    env = BradleyTerryFull(sigma=sigma)

    teams = set(X_train_weights[:, 0]).union(set(X_train_weights[:, 1]))
    team_ratings = dict(zip(teams, [env.rating() for _ in range(len(teams))]))
    hfa = env.rating(mu=hfa_mu, sigma=0.0)

    # iterate through games
    for winner, loser, location, weight in X_train_weights:
        winner_rating = team_ratings[winner]
        loser_rating = team_ratings[loser]
        if location == 1:
            [[winner_post, _], [loser_post]] = env.rate([[winner_rating, hfa], [loser_rating]])
        elif location == -1:
            [[winner_post], [loser_post, _]] = env.rate([[winner_rating], [loser_rating, hfa]])
        else:
            [[winner_post], [loser_post]] = env.rate([[winner_rating], [loser_rating]])

        winner_mu_adjustment = (winner_post.mu - winner_rating.mu)*weight
        winner_sigma_adjustment = (winner_post.sigma - winner_rating.sigma)*weight
        team_ratings[winner] = env.rating(mu=winner_rating.mu + winner_mu_adjustment, sigma=winner_rating.sigma + winner_sigma_adjustment)

        loser_mu_adjustment = (loser_post.mu - loser_rating.mu)*weight
        loser_sigma_adjustment = (loser_post.sigma - loser_rating.sigma)*weight
        team_ratings[loser] = env.rating(mu=loser_rating.mu + loser_mu_adjustment, sigma=loser_rating.sigma + loser_sigma_adjustment)

    return env, team_ratings

In [6]:
hfa_mu = 0.50
sigma = 25/3
minimum = 2/3
maximum = 4/3


X_train = df[['Team', 'Opponent', 'Location']].to_numpy()
weights = rescale_weights(df['Adjusted Score Differential'].to_numpy(), minimum, maximum)

X_train_weights = np.column_stack((X_train, weights))

env, team_ratings = get_season_ratings(X_train_weights, sigma, hfa_mu)

len(team_ratings)

364

In [7]:
df_ratings = pd.DataFrame(
    {
        'Team': team_ratings.keys(),
        'Mu': [v.mu for v in team_ratings.values()],
        'Sigma': [v.sigma for v in team_ratings.values()],
    }
)

df_ratings['OS Rating'] = df_ratings['Mu'] - df_ratings['Sigma']*3

df_ratings.sort_values(['OS Rating', 'Mu'], ascending=False, ignore_index=True, inplace=True)

df_ratings.head(50)

                     Team         Mu     Sigma  OS Rating
0                 Florida  54.679701  4.050711  42.527567
1                 Houston  53.363520  4.112330  41.026530
2                    Duke  52.239030  4.300482  39.337585
3         St. John's (NY)  51.065818  4.263783  38.274469
4                  Auburn  50.619677  4.177406  38.087458
5          Michigan State  49.544941  4.047617  37.402089
6               Tennessee  49.381903  4.066610  37.182071
7                 Alabama  48.414499  3.953111  36.555166
8                Maryland  45.863272  4.059376  33.685143
9                 Clemson  45.997767  4.223886  33.326110
10             Louisville  45.568786  4.110359  33.237708
11  Virginia Commonwealth  45.652538  4.141272  33.228721
12      Saint Mary's (CA)  46.183683  4.341960  33.157804
13                Gonzaga  45.198628  4.052997  33.039637
14               Michigan  44.919847  3.986598  32.960054
15              Wisconsin  44.295727  3.913025  32.556651
16           UC San Diego  45.958621  4.495992  32.470646
17                  Drake  46.300463  4.645006  32.365445
18             Texas Tech  44.076270  4.164664  31.582277
19          Brigham Young  43.190108  3.875843  31.562578
20                Arizona  42.952883  3.864665  31.358889
21                Memphis  44.371792  4.368654  31.265829
22         Colorado State  43.097252  3.972083  31.181004
23               Kentucky  41.845098  3.992224  29.868427
24              Texas A&M  42.224968  4.123852  29.853412
25                 Oregon  41.716162  4.055836  29.548655
26               Illinois  41.102939  3.861585  29.518184
27             Iowa State  41.448709  4.045257  29.312938
28            Mississippi  41.597089  4.127522  29.214524
29              Creighton  41.106151  4.005833  29.088653
30            Connecticut  41.303379  4.119202  28.945773
31               Missouri  40.895347  3.987928  28.931564
32                 Purdue  40.521343  3.872024  28.905272
33             New Mexico  41.652929  4.365823  28.555459
34                   UCLA  39.916070  4.012902  27.877364
35                Liberty  41.044985  4.390827  27.872505
36           George Mason  40.147106  4.162098  27.660812
37            Boise State  39.526973  4.096251  27.238220
38                Georgia  39.517901  4.103759  27.206623
39      Mississippi State  38.941902  3.994304  26.958992
40         North Carolina  38.590445  3.999915  26.590701
41               Oklahoma  38.761194  4.107846  26.437657
42             High Point  39.800229  4.477766  26.366930
43                 Xavier  38.641967  4.121795  26.276580
44              Marquette  38.692149  4.161555  26.207484
45               Arkansas  38.658931  4.174391  26.135758
46                 Kansas  37.938757  3.952869  26.080150
47             Utah State  38.931813  4.389185  25.764258
48              UC Irvine  38.623373  4.396891  25.432700
49                   Yale  38.717076  4.483968  25.265174

In [8]:
df_ratings.to_parquet(f'../data/preprocessed/mens_os_rankings/os_rankings_{SEASON}.parquet')

'Done'

'Done'