# Men's Starters

Get ratings of each team's starters in a given year. This file needs to be ran for every relevant season.

### Data Setup

In [ ]:
import pandas as pd

season = 2024

df = pd.read_parquet(f'../data/unprocessed/mens_starters/starters_{season}.parquet')

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Team Starters,Opponent Starters,...,Team Starter 3,Team Starter 4,Team Starter 5,Opponent Starter 1,Opponent Starter 2,Opponent Starter 3,Opponent Starter 4,Opponent Starter 5,Score Differential,Adjusted Score Differential
0,2023-11-06,Abilene Christian,-1,Oklahoma State,1,0,64,59,A. Dibba · H. Madden · K. McClain · A. Simmons...,J. Hicklen · M. Marsh · B. Thompson · Q. Willi...,...,Abilene Christian K. McClain,Abilene Christian A. Simmons,Abilene Christian C. Steele,Oklahoma State J. Hicklen,Oklahoma State M. Marsh,Oklahoma State B. Thompson,Oklahoma State Q. Williams,Oklahoma State J. Wright,5,1.253292
1,2023-11-10,Abilene Christian,-1,NC State,-1,0,64,84,A. Dibba · H. Madden · K. McClain · A. Simmons...,D. Burns · M. Diarra · D. Horne · C. Morsell ·...,...,Abilene Christian K. McClain,Abilene Christian A. Simmons,Abilene Christian C. Steele,NC State D. Burns,NC State M. Diarra,NC State D. Horne,NC State C. Morsell,NC State J. Taylor,-20,1.500000
2,2023-11-14,Abilene Christian,1,Prairie View,-1,0,74,79,A. Dibba · A. Igiehon · H. Madden · K. McClain...,"C. Felix, Jr. · N. Gazelas · B. Myles · A. Nun...",...,Abilene Christian H. Madden,Abilene Christian K. McClain,Abilene Christian C. Steele,"Prairie View C. Felix, Jr.",Prairie View N. Gazelas,Prairie View B. Myles,Prairie View A. Nunley,Prairie View C. Smith,-5,1.253292
3,2023-11-17,Abilene Christian,0,San Jose State,1,0,77,71,N. DeGruy · A. Dibba · H. Madden · A. Simmons ...,M. Amey · T. Anderson · A. Cardenas · A. Diong...,...,Abilene Christian H. Madden,Abilene Christian A. Simmons,Abilene Christian C. Steele,San Jose State M. Amey,San Jose State T. Anderson,San Jose State A. Cardenas,San Jose State A. Diongue,San Jose State T. Gorener,6,1.285760
4,2023-11-19,Abilene Christian,0,Fordham,1,0,59,45,N. DeGruy · A. Dibba · H. Madden · A. Simmons ...,A. Charlton · J. Medor · J. Rivera · K. Rose ·...,...,Abilene Christian H. Madden,Abilene Christian A. Simmons,Abilene Christian C. Steele,Fordham A. Charlton,Fordham J. Medor,Fordham J. Rivera,Fordham K. Rose,Fordham A. Tsimbila,14,1.448039
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11233,2024-02-17,Youngstown State,-1,Cleveland State,-1,0,73,81,D. Burns · B. Langdon · Z. Reid · B. Rush · B....,D. Arnett · T. Enaruna · D. Lowder · T. Willia...,...,Youngstown State Z. Reid,Youngstown State B. Rush,Youngstown State B. Thompson,Cleveland State D. Arnett,Cleveland State T. Enaruna,Cleveland State D. Lowder,Cleveland State T. Williams,Cleveland State J. Woodrich,-8,1.338710
11234,2024-02-23,Youngstown State,-1,Milwaukee,1,1,84,80,D. Burns · G. Dynes · B. Langdon · Z. Reid · B...,F. Fields · B. Freeman · D. Ham · E. Pratt · K...,...,Youngstown State B. Langdon,Youngstown State Z. Reid,Youngstown State B. Thompson,Milwaukee F. Fields,Milwaukee B. Freeman,Milwaukee D. Ham,Milwaukee E. Pratt,Milwaukee K. Pullian,4,1.214668
11235,2024-02-25,Youngstown State,-1,Green Bay,1,0,71,59,D. Burns · G. Dynes · B. Langdon · Z. Reid · B...,R. Byhre · C. Cummings · D. Douglas Jr. · E. J...,...,Youngstown State B. Langdon,Youngstown State Z. Reid,Youngstown State B. Thompson,Green Bay R. Byhre,Green Bay C. Cummings,Green Bay D. Douglas Jr.,Green Bay E. Jones,Green Bay P. Ruedinger,12,1.417062
11236,2024-02-28,Youngstown State,1,Detroit Mercy,1,0,69,55,D. Burns · G. Dynes · B. Langdon · Z. Reid · B...,E. Del Cadia · E. Kuac · M. Manciel · J. Stone...,...,Youngstown State B. Langdon,Youngstown State Z. Reid,Youngstown State B. Thompson,Detroit Mercy E. Del Cadia,Detroit Mercy E. Kuac,Detroit Mercy M. Manciel,Detroit Mercy J. Stone,Detroit Mercy M. Tankersley,14,1.448039
11237,2024-03-07,Youngstown State,1,Cleveland State,-1,0,70,82,D. Burns · G. Dynes · B. Langdon · Z. Reid · B...,D. Arnett · D. Lowder · T. Smith · T. Williams...,...,Youngstown State B. Langdon,Youngstown State Z. Reid,Youngstown State B. Thompson,Cleveland State D. Arnett,Cleveland State D. Lowder,Cleveland State T. Smith,Cleveland State T. Williams,Cleveland State J. Woodrich,-12,1.417062

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11238 entries, 0 to 11237
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         11238 non-null  datetime64[ns]
 1   Team                         11238 non-null  object
 2   Location                     11238 non-null  int8
 3   Opponent                     11238 non-null  object
 4   Result                       11238 non-null  int8
 5   Overtime                     11238 non-null  int8
 6   Team Score                   11238 non-null  int64
 7   Opponent Score               11238 non-null  int64
 8   Team Starters                11238 non-null  object
 9   Opponent Starters            11238 non-null  object
 10  Team Starter 1               11238 non-null  object
 11  Team Starter 2               11238 non-null  object
 12  Team Starter 3               11238 non-null  object
 13  Team Starter 4               11238 non-null  object
 14  Team Starter 5               11238 non-null  object
 15  Opponent Starter 1           11238 non-null  object
 16  Opponent Starter 2           11238 non-null  object
 17  Opponent Starter 3           11238 non-null  object
 18  Opponent Starter 4           11238 non-null  object
 19  Opponent Starter 5           11238 non-null  object
 20  Score Differential           11238 non-null  int64
 21  Adjusted Score Differential  11238 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(3), int8(3), object(14)
memory usage: 1.7+ MB

### Model Building

##### Starters Ratings

Unfortunately, there is no way to differentiate between 2 starters with the same name on the same team. In such circumstances, we double count the entity.

In [3]:
X = (
    pd.get_dummies(df['Team Starter 1']).astype('int8')
).add(
    pd.get_dummies(df['Team Starter 2']).astype('int8'), fill_value=0
).add(
    pd.get_dummies(df['Team Starter 3']).astype('int8'), fill_value=0 
).add(
    pd.get_dummies(df['Team Starter 4']).astype('int8'), fill_value=0 
).add(
    pd.get_dummies(df['Team Starter 5']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 1']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 2']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 3']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 4']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 5']).astype('int8'), fill_value=0 
)

X['Home Field Advantage'] = df['Location'].copy()

X

C:\Users\mhugh\AppData\Local\Temp\ipykernel_17296\563957636.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X['Home Field Advantage'] = df['Location'].copy()

,Abilene Christian A. Dibba,Abilene Christian A. Igiehon,Abilene Christian A. Simmons,Abilene Christian C. Steele,Abilene Christian H. Madden,Abilene Christian J. Seat,Abilene Christian K. McClain,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Air Force B. Becker,...,Yale N. Townsend,Yale Y. Basa-Ama,Youngstown State B. Langdon,Youngstown State B. Rush,Youngstown State B. Thompson,Youngstown State D. Burns,Youngstown State E. Farmer,Youngstown State G. Dynes,Youngstown State Z. Reid,Home Field Advantage
0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
1,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
2,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11233,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,-1
11234,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,-1
11235,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,-1
11236,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1
11237,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1

In [4]:
import numpy as np
from sklearn.model_selection import GroupKFold

def get_gkf_data(X, y, w, groups, cv=3):
    """
    Converts training data to list of folds
    """
    np.random.seed(22)
    gkf = GroupKFold(n_splits=cv)

    data = []
    for train_index, test_index in gkf.split(X, y, groups=groups):
        X_train = X[train_index]
        X_test = X[test_index]

        y_train = y[train_index]
        y_test = y[test_index]

        # sample weights
        w_train = w[train_index]

        data.append((X_train, X_test, y_train, y_test, w_train))

    return data

cv_data = get_gkf_data(X.to_numpy(), df['Result'].to_numpy(), df['Adjusted Score Differential'].to_numpy(), df['Date'].to_numpy())

len(cv_data)

3

In [5]:
def rescale_weights(arr, minimum, maximum):
    """
    Rescale the weights array to match desired weights.
    Assumes the data is already transformed where a 1 point win is 1.00, a blowout is 1.50, and a tie is 0.50.
    Ties will be weighted as half the minimum.
    """

    arr_scaled = ((arr - 1.00) / 0.50) * (maximum - minimum) + minimum
    arr_scaled[arr == 0.50] = minimum / 2
    return arr_scaled

In [6]:
from sklearn.metrics import log_loss
from sklearn.linear_model import LogisticRegression
import warnings
import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective(trial, cv_data=cv_data):
    # model tuning
    C = trial.suggest_float('C', 0.1, 10, log=True)
    mod = LogisticRegression(penalty='l2', C=C, fit_intercept=False)
    minimum = trial.suggest_float('minimum', 0.1, 1.0, step=0.1)
    maximum = trial.suggest_float('maximum', 1.0, 8.0, step=0.5)

    # cross validation
    y_actuals = []
    y_preds = []
    for X_train, X_test, y_train, y_test, w_train in cv_data:
        y_actuals.append(y_test)

        weights = rescale_weights(w_train, minimum, maximum)

        with warnings.catch_warnings():
            warnings.filterwarnings('ignore')  # prevent convergence warnings
            mod.fit(X_train, y_train, sample_weight=weights)

        y_preds.append(mod.predict_proba(X_test)[:, 1])

    return log_loss(np.hstack(y_actuals), np.hstack(y_preds))

study = optuna.create_study(direction='minimize', sampler=optuna.samplers.TPESampler(seed=22))
study.optimize(objective, n_trials=100, show_progress_bar=True)

study.best_params

  0%|          | 0/100 [00:00<?, ?it/s]

{'C': 0.10000649881806253, 'minimum': 0.30000000000000004, 'maximum': 1.5}

In [7]:
minimum = study.best_params['minimum']
maximum = study.best_params['maximum']

weight = rescale_weights(df['Adjusted Score Differential'], minimum, maximum)

mod = LogisticRegression(penalty='l2', C=study.best_params['C'], fit_intercept=False)

mod.fit(X, df['Result'], sample_weight=weight)

df_ratings = pd.DataFrame(
    {
        'Starter': X.columns,
        'Rating': mod.coef_[0]
    }
).sort_values(by=['Rating'], ascending=False, ignore_index=True)

df_ratings_display = df_ratings.loc[df_ratings['Starter'] != 'Home Field Advantage', :].reset_index(drop=True)
df_ratings_display.index += 1

df_ratings_display.head(25)

                          Starter    Rating
1              Kentucky D. Wagner  0.632413
2          Connecticut C. Spencer  0.616515
3           Connecticut T. Newton  0.616515
4              Auburn A. Holloway  0.584102
5                Houston J. Shead  0.550119
6              Houston J. Francis  0.550119
7                Houston L. Cryer  0.550119
8                 Auburn D. Jones  0.546752
9           Connecticut S. Castle  0.543757
10               Duke M. Mitchell  0.539086
11                Purdue B. Smith  0.536821
12                Purdue F. Loyer  0.536821
13                Purdue L. Jones  0.536821
14         Purdue T. Kaufman-Renn  0.536821
15                 Purdue Z. Edey  0.536821
16             Houston J. Roberts  0.536116
17         Connecticut A. Karaban  0.530060
18  Appalachian State T. Spillers  0.506440
19        North Carolina R. Davis  0.503451
20        North Carolina A. Bacot  0.503451
21      Nevada-Las Vegas K. Boone  0.488433
22     Appalachian State X. Brown  0.488039
23         South Florida K. Pryor  0.486813
24             Colgate B. Cummins  0.485713
25           UT Arlington A. Cash  0.485635

### Miscellaneous

##### Save Rankings

Get last available lineup for each team

In [8]:
starter_to_rating = dict(zip(df_ratings_display['Starter'], df_ratings_display['Rating']))

len(starter_to_rating)

3201

In [9]:
df_last_starters = (
    df
    .sort_values(by=['Date']).groupby(['Team'])
    .tail(1)
    .reset_index(drop=True)[['Team'] + [f'Team Starter {i}' for i in range(1, 6)]]
)

df_last_starters

,Team,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5
0,Chicago State,Chicago State W. Cardet,Chicago State J. Corbett,Chicago State N. Crawford,Chicago State B. Davis,Chicago State C. Jernigan
1,Bellarmine,Bellarmine L. Hatton,Bellarmine B. Johnson,Bellarmine P. Suder,Bellarmine G. Tipton,Bellarmine B. Wieland
2,Central Arkansas,Central Arkansas T. Anderson,Central Arkansas E. Cato,Central Arkansas I. Klintman,Central Arkansas M. Olowokere,Central Arkansas D. Sofield
3,Tennessee Tech,Tennessee Tech J. Davis,Tennessee Tech D. Egbuniwe,Tennessee Tech J. Harvey,Tennessee Tech K. Layton,Tennessee Tech D. Wood
4,Lindenwood,Lindenwood D. Beane,Lindenwood K. Cole,Lindenwood K. Haymon,Lindenwood J. McDaniel,Lindenwood C. Ruffin
...,...,...,...,...,...,...
357,South Florida,South Florida K. Knox,South Florida J. Placer,South Florida K. Pryor,South Florida B. Stroud,South Florida C. Youngblood
358,Providence,Providence G. Dual,Providence C. Floyd,Providence D. Gaines,Providence J. Oduro,Providence J. Pierre
359,Virginia,Virginia R. Beekman,Virginia R. Dunn,Virginia I. McKneely,Virginia J. Minor,Virginia T. Murray
360,Wagner,Wagner T. Allen,Wagner J. Brown,Wagner M. Council Jr.,Wagner J. Ezquerra,Wagner K. Lewis
361,North Texas,North Texas J. Buggs,North Texas J. Edwards,North Texas R. Jones,North Texas A. Scott,North Texas M. Sissoko

In [10]:
for i in range(1, 6):
    df_last_starters[f'Team Starter {i} Rating'] = df_last_starters[f'Team Starter {i}'].map(starter_to_rating)

df_last_starters['Rating'] = df_last_starters[[f'Team Starter {i} Rating' for i in range(1, 6)]].mean(axis=1)

df_last_starters

,Team,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5,Team Starter 1 Rating,Team Starter 2 Rating,Team Starter 3 Rating,Team Starter 4 Rating,Team Starter 5 Rating,Rating
0,Chicago State,Chicago State W. Cardet,Chicago State J. Corbett,Chicago State N. Crawford,Chicago State B. Davis,Chicago State C. Jernigan,-0.247432,-0.210814,0.182711,-0.342508,-0.035390,-0.130687
1,Bellarmine,Bellarmine L. Hatton,Bellarmine B. Johnson,Bellarmine P. Suder,Bellarmine G. Tipton,Bellarmine B. Wieland,-0.337395,-0.146326,-0.337395,-0.337395,-0.137783,-0.259259
2,Central Arkansas,Central Arkansas T. Anderson,Central Arkansas E. Cato,Central Arkansas I. Klintman,Central Arkansas M. Olowokere,Central Arkansas D. Sofield,-0.210708,-0.627764,-0.132358,-0.412960,-0.115108,-0.299780
3,Tennessee Tech,Tennessee Tech J. Davis,Tennessee Tech D. Egbuniwe,Tennessee Tech J. Harvey,Tennessee Tech K. Layton,Tennessee Tech D. Wood,-0.292388,-0.226013,-0.248714,-0.133562,-0.220292,-0.224194
4,Lindenwood,Lindenwood D. Beane,Lindenwood K. Cole,Lindenwood K. Haymon,Lindenwood J. McDaniel,Lindenwood C. Ruffin,-0.444948,-0.539598,0.072419,-0.222966,-0.280004,-0.283019
...,...,...,...,...,...,...,...,...,...,...,...,...
357,South Florida,South Florida K. Knox,South Florida J. Placer,South Florida K. Pryor,South Florida B. Stroud,South Florida C. Youngblood,0.316594,0.019504,0.486813,0.243912,0.272402,0.267845
358,Providence,Providence G. Dual,Providence C. Floyd,Providence D. Gaines,Providence J. Oduro,Providence J. Pierre,-0.217080,-0.003679,0.163292,0.201794,0.077603,0.044386
359,Virginia,Virginia R. Beekman,Virginia R. Dunn,Virginia I. McKneely,Virginia J. Minor,Virginia T. Murray,0.214592,0.214592,0.162870,0.097564,-0.140167,0.109890
360,Wagner,Wagner T. Allen,Wagner J. Brown,Wagner M. Council Jr.,Wagner J. Ezquerra,Wagner K. Lewis,0.075493,0.088210,-0.041685,-0.113368,-0.113368,-0.020944
361,North Texas,North Texas J. Buggs,North Texas J. Edwards,North Texas R. Jones,North Texas A. Scott,North Texas M. Sissoko,0.112895,0.211638,0.227467,0.188539,0.188539,0.185816

In [11]:
df_sheet = df_last_starters[['Team', 'Rating']].copy().sort_values(by=['Rating'], ascending=False, ignore_index=True)

df_sheet.head(25)

                 Team    Rating
0         Connecticut  0.548104
1              Purdue  0.536821
2             Houston  0.496831
3              Auburn  0.483800
4      North Carolina  0.441960
5       McNeese State  0.416066
6       James Madison  0.415976
7            Illinois  0.409751
8           Tennessee  0.403746
9             Arizona  0.387775
10            Gonzaga  0.386974
11              Drake  0.386261
12       Grand Canyon  0.385846
13         Iowa State  0.382822
14      Indiana State  0.380778
15          Princeton  0.367084
16             Nevada  0.366231
17             Dayton  0.366057
18     South Carolina  0.358905
19         New Mexico  0.351988
20            Samford  0.351516
21     Colorado State  0.350183
22          Creighton  0.341913
23  Appalachian State  0.340323
24           Kentucky  0.338157

In [ ]:
df_sheet.to_parquet(f'../data/preprocessed/mens_starters/starters_{season}.parquet')

'Done'

'Done'