# Openskill Ratings

Calculate ratings using openskill algorithm for a given season. This file needs to be ran for every relevant season (starting in 2012).

In [1]:
SEASON = 2012

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df = pd.read_parquet(fr'..\data\unprocessed\mens_sports_reference\full_season_sports_reference_{SEASON}.parquet')

df = df.loc[df['NCAA Tournament'] == 0, :].reset_index(drop=True)  # only include games before NCAA Tournament

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,Air Force,2011-11-11,0,1,Army,REG (Non-Conf),1,87,71,29,52,0.558,3,14,0.214,26,38,0.684,0.587,26,36,0.722,7,30,37,25,15,1,23,25,23.0,58.0,0.397,6.0,29.0,0.207,17.0,29.0,0.586,0.448,19.0,26.0,0.731,6.0,18.0,24.0,13.0,11.0,0.0,24.0,29.0,0,0,16,1.475419,85.64,1.015880,0.829052,85.640000
1,Air Force,2011-11-12,0,0,Virginia Military Institute,REG (Non-Conf),1,75,65,28,56,0.500,6,22,0.273,22,34,0.647,0.554,13,18,0.722,11,29,40,20,5,4,14,16,22.0,56.0,0.393,10.0,30.0,0.333,12.0,26.0,0.462,0.482,11.0,15.0,0.733,6.0,19.0,25.0,11.0,6.0,4.0,14.0,21.0,0,0,10,1.381279,68.76,1.090750,0.945317,68.760000
2,Air Force,2011-11-23,0,1,Colorado,REG (Non-Conf),-1,73,76,25,62,0.403,5,19,0.263,20,43,0.465,0.444,18,25,0.720,10,16,26,14,9,4,6,14,29.0,60.0,0.483,10.0,24.0,0.417,19.0,36.0,0.528,0.567,8.0,14.0,0.571,12.0,30.0,42.0,15.0,1.0,4.0,17.0,22.0,1,1,-3,1.166625,70.08,1.041667,1.084475,62.293333
3,Air Force,2011-12-03,0,-1,Drake,REG (Non-Conf),-1,60,62,16,41,0.390,6,15,0.400,10,26,0.385,0.463,22,35,0.629,4,23,27,6,9,2,15,24,18.0,45.0,0.400,6.0,20.0,0.300,12.0,25.0,0.480,0.467,20.0,31.0,0.645,5.0,25.0,30.0,8.0,9.0,4.0,13.0,26.0,0,0,-2,1.102120,67.02,0.895255,0.925097,67.020000
4,Air Force,2011-12-07,0,1,Wright State,REG (Non-Conf),1,55,34,19,45,0.422,9,25,0.360,10,20,0.500,0.522,8,12,0.667,3,25,28,15,7,4,12,15,9.0,46.0,0.196,2.0,19.0,0.105,7.0,27.0,0.259,0.217,14.0,18.0,0.778,9.0,22.0,31.0,4.0,5.0,5.0,16.0,14.0,0,0,21,1.500000,60.10,0.915141,0.565724,60.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10555,Youngstown State,2012-02-18,0,-1,Austin Peay,REG (Non-Conf),-1,68,71,24,56,0.429,13,29,0.448,11,27,0.407,0.545,7,10,0.700,9,19,28,13,6,7,14,18,22.0,66.0,0.333,6.0,22.0,0.273,16.0,44.0,0.364,0.379,21.0,27.0,0.778,24.0,23.0,47.0,10.0,5.0,1.0,13.0,16.0,0,0,-3,1.166625,66.14,1.028122,1.073480,66.140000
10556,Youngstown State,2012-02-23,0,1,Wright State,REG (Conf),1,61,54,22,49,0.449,6,19,0.316,16,30,0.533,0.510,11,16,0.688,5,29,34,14,5,7,14,15,18.0,56.0,0.321,8.0,23.0,0.348,10.0,33.0,0.303,0.393,10.0,19.0,0.526,12.0,24.0,36.0,11.0,11.0,1.0,15.0,16.0,0,0,7,1.313867,66.20,0.921450,0.815710,66.200000
10557,Youngstown State,2012-02-25,0,1,Detroit Mercy,REG (Conf),-1,74,76,23,50,0.460,11,26,0.423,12,24,0.500,0.570,17,22,0.773,5,16,21,13,5,0,12,13,29.0,51.0,0.569,7.0,16.0,0.438,22.0,35.0,0.629,0.637,11.0,14.0,0.786,5.0,19.0,24.0,18.0,5.0,4.0,11.0,24.0,0,0,-2,1.102120,64.92,1.139864,1.170672,64.920000
10558,Youngstown State,2012-02-28,0,1,Green Bay,CTOURN,1,77,60,29,61,0.475,10,23,0.435,19,38,0.500,0.557,9,13,0.692,10,18,28,17,13,5,6,10,24.0,53.0,0.453,4.0,12.0,0.333,20.0,41.0,0.488,0.491,8.0,10.0,0.800,8.0,21.0,29.0,15.0,3.0,1.0,17.0,15.0,0,0,17,1.488021,64.56,1.192689,0.929368,64.560000
10559,Youngstown State,2012-03-02,0,0,Detroit Mercy,CTOURN,-1,76,93,29,53,0.547,6,20,0.300,23,33,0.697,0.604,12,22,0.545,6,15,21,16,4,2,15,20,33.0,55.0,0.600,8.0,17.0,0.471,25.0,38.0,0.658,0.673,19.0,25.0,0.760,7.0,21.0,28.0,16.0,7.0,2.0,13.0,21.0,0,0,-17,1.488021,71.84,1.057906,1.294543,71.840000

Filter to just wins because I don't need duplicate perspectives

In [3]:
df = df.loc[
    df['Result'] == 1, 
    ['Date', 'Team', 'Location', 'Opponent', 'Result', 'Adjusted Score Differential']
].reset_index(drop=True)

df.sort_values(['Date'], inplace=True, ignore_index=True)

df

,Date,Team,Location,Opponent,Result,Adjusted Score Differential
0,2011-11-07,Arizona,1,Valparaiso,1,1.361013
1,2011-11-07,St. John's (NY),1,William & Mary,1,1.462122
2,2011-11-07,Mississippi State,1,Eastern Kentucky,1,1.381279
3,2011-11-09,St. John's (NY),1,Lehigh,1,1.253292
4,2011-11-09,Arizona,1,Duquesne,1,1.338710
...,...,...,...,...,...,...
5275,2012-03-14,Utah State,1,Cal State Bakersfield,1,1.285760
5276,2012-03-14,Buffalo,-1,American,1,1.488021
5277,2012-03-14,Fairfield,1,Yale,1,1.417062
5278,2012-03-14,Northern Iowa,-1,Saint Joseph's,1,1.102120
5279,2012-03-14,Oregon State,1,Western Illinois,1,1.500000

In [4]:
def rescale_weights(arr, minimum, maximum):
    """
    Rescale the weights array to match desired weights.
    Assumes the data is already transformed where a 1 point win is 1.00, a blowout is 1.50, and a tie is 0.50.
    Ties will be weighted as half the minimum.
    """

    arr_scaled = ((arr - 1.00) / 0.50) * (maximum - minimum) + minimum
    arr_scaled[arr == 0.50] = minimum / 2
    return arr_scaled

In [5]:
from typing import Tuple
from openskill.models import BradleyTerryFull
import numpy as np

def get_season_ratings(X_train_weights: np.array, sigma: float, hfa_mu: float) -> Tuple[BradleyTerryFull, dict]:
    """
    Run the algorithm over the course of a season.

    Args:
        X_train_weights (np.array): Numpy array where each row is a game and columns are Winner, Loser, Location, Weight.
        sigma (float): The starting variance for each team rating.
        hfa_mu (float): The mu of home field advantage.

    Returns:
        Tuple[BradleyTerryFull, dict]: The environment object and dictionary of team ratings.
    """
    # initialize
    env = BradleyTerryFull(sigma=sigma)

    teams = set(X_train_weights[:, 0]).union(set(X_train_weights[:, 1]))
    team_ratings = dict(zip(teams, [env.rating() for _ in range(len(teams))]))
    hfa = env.rating(mu=hfa_mu, sigma=0.0)

    # iterate through games
    for winner, loser, location, weight in X_train_weights:
        winner_rating = team_ratings[winner]
        loser_rating = team_ratings[loser]
        if location == 1:
            [[winner_post, _], [loser_post]] = env.rate([[winner_rating, hfa], [loser_rating]])
        elif location == -1:
            [[winner_post], [loser_post, _]] = env.rate([[winner_rating], [loser_rating, hfa]])
        else:
            [[winner_post], [loser_post]] = env.rate([[winner_rating], [loser_rating]])

        winner_mu_adjustment = (winner_post.mu - winner_rating.mu)*weight
        winner_sigma_adjustment = (winner_post.sigma - winner_rating.sigma)*weight
        team_ratings[winner] = env.rating(mu=winner_rating.mu + winner_mu_adjustment, sigma=winner_rating.sigma + winner_sigma_adjustment)

        loser_mu_adjustment = (loser_post.mu - loser_rating.mu)*weight
        loser_sigma_adjustment = (loser_post.sigma - loser_rating.sigma)*weight
        team_ratings[loser] = env.rating(mu=loser_rating.mu + loser_mu_adjustment, sigma=loser_rating.sigma + loser_sigma_adjustment)

    return env, team_ratings

In [6]:
hfa_mu = 0.50
sigma = 25/3
minimum = 2/3
maximum = 4/3


X_train = df[['Team', 'Opponent', 'Location']].to_numpy()
weights = rescale_weights(df['Adjusted Score Differential'].to_numpy(), minimum, maximum)

X_train_weights = np.column_stack((X_train, weights))

env, team_ratings = get_season_ratings(X_train_weights, sigma, hfa_mu)

len(team_ratings)

344

In [7]:
df_ratings = pd.DataFrame(
    {
        'Team': team_ratings.keys(),
        'Mu': [v.mu for v in team_ratings.values()],
        'Sigma': [v.sigma for v in team_ratings.values()],
    }
)

df_ratings['OS Rating'] = df_ratings['Mu'] - df_ratings['Sigma']*3

df_ratings.sort_values(['OS Rating', 'Mu'], ascending=False, ignore_index=True, inplace=True)

df_ratings.head(50)

                     Team         Mu     Sigma  OS Rating
0                Kentucky  52.874948  4.471622  39.460082
1                Syracuse  52.172554  4.536290  38.563683
2          Michigan State  49.305377  4.029564  37.216686
3                Missouri  49.958466  4.310026  37.028387
4          North Carolina  48.170494  4.200933  35.567693
5                  Kansas  47.996350  4.194005  35.414335
6              Ohio State  47.212131  3.991023  35.239062
7                  Baylor  45.293965  4.173032  32.774870
8              Louisville  44.391650  3.978946  32.454813
9                 Memphis  44.577476  4.048165  32.432981
10             Vanderbilt  44.358134  4.001982  32.352189
11             New Mexico  44.786159  4.163003  32.297149
12          Wichita State  45.063515  4.348984  32.016563
13              Wisconsin  43.885737  4.039818  31.766281
14          Florida State  43.557671  4.019547  31.499030
15           Murray State  46.809288  5.130272  31.418472
16                Indiana  42.983654  4.060369  30.802547
17                   Duke  43.688335  4.299669  30.789327
18              Marquette  42.984280  4.110404  30.653067
19             Cincinnati  42.469912  4.089085  30.202657
20              Creighton  43.283048  4.381885  30.137393
21               Michigan  42.036607  4.028786  29.950250
22  Virginia Commonwealth  42.813105  4.330770  29.820796
23                Gonzaga  42.668496  4.427579  29.385760
24                 Drexel  41.799566  4.227200  29.117967
25            Saint Louis  41.400820  4.234280  28.697979
26      Saint Mary's (CA)  42.223047  4.526608  28.643223
27        San Diego State  41.715581  4.377812  28.582144
28                 Temple  41.210593  4.230268  28.519789
29                Florida  40.348207  4.103183  28.038657
30             Notre Dame  40.081033  4.022512  28.013498
31             Georgetown  40.505421  4.182516  27.957874
32       Nevada-Las Vegas  40.519519  4.253335  27.759515
33             Iowa State  39.867819  4.116065  27.519624
34           Kansas State  39.495901  4.205981  26.877959
35          South Florida  38.458458  3.975670  26.531448
36     South Dakota State  39.138592  4.223693  26.467513
37                 Purdue  38.447268  4.020621  26.385405
38                Harvard  40.728899  4.862670  26.140888
39           Oral Roberts  39.236136  4.497728  25.742953
40                 Nevada  39.146721  4.487492  25.684243
41                 Oregon  38.176667  4.170181  25.666123
42                Belmont  38.711591  4.373890  25.589921
43                   Ohio  38.458096  4.333708  25.456972
44        St. Bonaventure  37.514546  4.041446  25.390207
45                Alabama  37.483615  4.052315  25.326671
46       Long Beach State  38.853474  4.532381  25.256331
47                  Texas  37.450171  4.075556  25.223502
48              Tennessee  37.437281  4.099260  25.139502
49          Brigham Young  37.998893  4.323876  25.027265

In [8]:
df_ratings.to_parquet(f'../data/preprocessed/mens_os_rankings/os_rankings_{SEASON}.parquet')

'Done'

'Done'