# Women's Starters

Get ratings of each team's starters in a given year. This file needs to be ran for every relevant season.

### Data Setup

In [1]:
import pandas as pd

season = 2012

df = pd.read_parquet(f'../data/unprocessed/womens_starters/starters_{season}.parquet')

df = df.loc[df['NCAA Tournament'] == 0, :].reset_index(drop=True)  # only include games before NCAA Tournament

df

,Date,NCAA Tournament,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Team Starters,...,Team Starter 3,Team Starter 4,Team Starter 5,Opponent Starter 1,Opponent Starter 2,Opponent Starter 3,Opponent Starter 4,Opponent Starter 5,Score Differential,Adjusted Score Differential
0,2011-11-11,0,Air Force,-1,Lipscomb,1,0,68,59,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Lipscomb A. Bowers,Lipscomb M. Faulkner,Lipscomb H. Phillips,Lipscomb O. Smith,Lipscomb E. Thornsberry,9,1.361013
1,2011-11-13,0,Air Force,-1,Tennessee-Martin,-1,0,60,84,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Tennessee-Martin H. Butler,Tennessee-Martin S. Crawford,Tennessee-Martin J. Haislip,Tennessee-Martin T. Hall,Tennessee-Martin J. Newsome,-24,1.500000
2,2011-11-17,0,Air Force,1,Denver,-1,0,52,54,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Denver M. Michel,Denver K. Murdoch,Denver Q. Noonan,Denver M. Shell,Denver E. Smith,-2,1.102120
3,2011-11-19,0,Air Force,-1,Texas Southern,1,0,64,54,D. James · A. Leipprandt · C. Medina · M. O'Ne...,...,Air Force C. Medina,Air Force M. O'Neil,Air Force C. Thompson,Texas Southern C. Anyiam,Texas Southern G. Fleming,Texas Southern A. Hall,Texas Southern J. McQueen,Texas Southern K. West,10,1.381279
4,2011-11-21,0,Air Force,-1,Texas State,1,0,77,69,D. James · A. Leipprandt · M. O'Neil · D. Sorr...,...,Air Force M. O'Neil,Air Force D. Sorrera,Air Force C. Thompson,Texas State D. Clinch,Texas State A. Ezeh,Texas State D. Ford,Texas State I. Johnson,Texas State V. Kalu,8,1.338710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10075,2012-02-18,0,Youngstown State,1,Green Bay,-1,1,72,77,B. Brown · K. Fickiesen · T. Jones · K. Middle...,...,Youngstown State T. Jones,Youngstown State K. Middlebrooks,Youngstown State M. Nortey,Green Bay L. Bauer,Green Bay M. Lukan,Green Bay H. Quilling,Green Bay A. Ritchie,Green Bay J. Wojta,-5,1.253292
10076,2012-02-23,0,Youngstown State,-1,Wright State,-1,0,62,84,B. Brown · K. Fickiesen · T. Jones · K. Middle...,...,Youngstown State T. Jones,Youngstown State K. Middlebrooks,Youngstown State M. Nortey,Wright State C. Boyd,Wright State K. Demmings,Wright State M. Fox,Wright State K. Lamotte,Wright State S. Sandifer,-22,1.500000
10077,2012-02-25,0,Youngstown State,-1,Detroit Mercy,-1,0,64,67,B. Brown · K. Fickiesen · L. Hornberger · K. M...,...,Youngstown State L. Hornberger,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Detroit Mercy L. Allen,Detroit Mercy S. Brown,Detroit Mercy M. Hatter,Detroit Mercy J. Jones,Detroit Mercy S. Shearer,-3,1.166625
10078,2012-03-03,0,Youngstown State,-1,Cleveland State,-1,0,69,79,B. Brown · K. Fickiesen · K. Middlebrooks · H....,...,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Youngstown State M. Touvelle,Cleveland State J. Adams,Cleveland State C. Coleman,Cleveland State T. Keane,Cleveland State H. King,Cleveland State S. Winton,-10,1.381279
10079,2012-03-05,0,Youngstown State,-1,Cleveland State,-1,0,56,59,B. Brown · K. Fickiesen · K. Middlebrooks · H....,...,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Youngstown State M. Thompson,Cleveland State J. Adams,Cleveland State C. Coleman,Cleveland State T. Keane,Cleveland State H. King,Cleveland State S. Winton,-3,1.166625

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10080 entries, 0 to 10079
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         10080 non-null  datetime64[ns]
 1   NCAA Tournament              10080 non-null  int32
 2   Team                         10080 non-null  object
 3   Location                     10080 non-null  int8
 4   Opponent                     10080 non-null  object
 5   Result                       10080 non-null  int8
 6   Overtime                     10080 non-null  int8
 7   Team Score                   10080 non-null  int64
 8   Opponent Score               10080 non-null  int64
 9   Team Starters                10080 non-null  object
 10  Opponent Starters            10080 non-null  object
 11  Team Starter 1               10080 non-null  object
 12  Team Starter 2               10080 non-null  object
 13  Team Starter 3               10080 non-null  object
 14  Team Starter 4               10080 non-null  object
 15  Team Starter 5               10080 non-null  object
 16  Opponent Starter 1           10080 non-null  object
 17  Opponent Starter 2           10080 non-null  object
 18  Opponent Starter 3           10080 non-null  object
 19  Opponent Starter 4           10080 non-null  object
 20  Opponent Starter 5           10080 non-null  object
 21  Score Differential           10080 non-null  int64
 22  Adjusted Score Differential  10080 non-null  float64
dtypes: datetime64[ns](1), float64(1), int32(1), int64(3), int8(3), object(14)
memory usage: 1.5+ MB

### Model Building

##### Starters Ratings

Unfortunately, there is no way to differentiate between 2 starters with the same name on the same team. In such circumstances, we double count the entity.

In [3]:
X = (
    pd.get_dummies(df['Team Starter 1']).astype('int8')
).add(
    pd.get_dummies(df['Team Starter 2']).astype('int8'), fill_value=0
).add(
    pd.get_dummies(df['Team Starter 3']).astype('int8'), fill_value=0 
).add(
    pd.get_dummies(df['Team Starter 4']).astype('int8'), fill_value=0 
).add(
    pd.get_dummies(df['Team Starter 5']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 1']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 2']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 3']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 4']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 5']).astype('int8'), fill_value=0 
)

X['Home Field Advantage'] = df['Location'].copy()

X

C:\Users\mhugh\AppData\Local\Temp\ipykernel_16568\563957636.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X['Home Field Advantage'] = df['Location'].copy()

,Air Force A. Leipprandt,Air Force A. Wilson,Air Force C. Medina,Air Force C. Thompson,Air Force D. James,Air Force D. Sorrera,Air Force J. Blagowsky,Air Force J. Satterfield,Air Force K. Bohannon,Air Force K. Hilbig,...,Youngstown State B. Brown,Youngstown State H. Schlegel,Youngstown State K. Fickiesen,Youngstown State K. Middlebrooks,Youngstown State L. Hornberger,Youngstown State M. Nortey,Youngstown State M. Thompson,Youngstown State M. Touvelle,Youngstown State T. Jones,Home Field Advantage
0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
1,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
2,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
4,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10075,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1
10076,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,-1
10077,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,-1
10078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,-1
10079,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,-1

In [4]:
import numpy as np
from sklearn.model_selection import GroupKFold

def get_gkf_data(X, y, w, groups, cv=3):
    """
    Converts training data to list of folds
    """
    np.random.seed(22)
    gkf = GroupKFold(n_splits=cv)

    data = []
    for train_index, test_index in gkf.split(X, y, groups=groups):
        X_train = X[train_index]
        X_test = X[test_index]

        y_train = y[train_index]
        y_test = y[test_index]

        # sample weights
        w_train = w[train_index]

        data.append((X_train, X_test, y_train, y_test, w_train))

    return data

cv_data = get_gkf_data(X.to_numpy(), df['Result'].to_numpy(), df['Adjusted Score Differential'].to_numpy(), df['Date'].to_numpy())

len(cv_data)

3

In [5]:
def rescale_weights(arr, minimum, maximum):
    """
    Rescale the weights array to match desired weights.
    Assumes the data is already transformed where a 1 point win is 1.00, a blowout is 1.50, and a tie is 0.50.
    Ties will be weighted as half the minimum.
    """

    arr_scaled = ((arr - 1.00) / 0.50) * (maximum - minimum) + minimum
    arr_scaled[arr == 0.50] = minimum / 2
    return arr_scaled

In [6]:
from sklearn.metrics import log_loss
from sklearn.linear_model import LogisticRegression
import warnings
import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective(trial, cv_data=cv_data):
    # model tuning
    C = trial.suggest_float('C', 0.1, 10, log=True)
    mod = LogisticRegression(penalty='l2', C=C, fit_intercept=False)
    minimum = trial.suggest_float('minimum', 0.1, 1.0, step=0.1)
    maximum = trial.suggest_float('maximum', 1.0, 8.0, step=0.5)

    # cross validation
    y_actuals = []
    y_preds = []
    for X_train, X_test, y_train, y_test, w_train in cv_data:
        y_actuals.append(y_test)

        weights = rescale_weights(w_train, minimum, maximum)

        with warnings.catch_warnings():
            warnings.filterwarnings('ignore')  # prevent convergence warnings
            mod.fit(X_train, y_train, sample_weight=weights)

        y_preds.append(mod.predict_proba(X_test)[:, 1])

    return log_loss(np.hstack(y_actuals), np.hstack(y_preds))

study = optuna.create_study(direction='minimize', sampler=optuna.samplers.TPESampler(seed=22))
study.optimize(objective, n_trials=100, show_progress_bar=True)

study.best_params

  0%|          | 0/100 [00:00<?, ?it/s]

{'C': 0.1083365065661173, 'minimum': 0.4, 'maximum': 3.0}

In [7]:
minimum = study.best_params['minimum']
maximum = study.best_params['maximum']

weight = rescale_weights(df['Adjusted Score Differential'], minimum, maximum)

mod = LogisticRegression(penalty='l2', C=study.best_params['C'], fit_intercept=False)

mod.fit(X, df['Result'], sample_weight=weight)

df_ratings = pd.DataFrame(
    {
        'Starter': X.columns,
        'Rating': mod.coef_[0]
    }
).sort_values(by=['Rating'], ascending=False, ignore_index=True)

df_ratings_display = df_ratings.loc[df_ratings['Starter'] != 'Home Field Advantage', :].reset_index(drop=True)
df_ratings_display.index += 1

df_ratings_display.head(25)

                        Starter    Rating
1              Baylor B. Griner  1.251268
2          Stanford C. Ogwumike  1.162526
3              Baylor K. Hayden  1.099782
4            Maryland A. Thomas  1.076184
5          Green Bay S. Eichler  1.042821
6           Stanford T. Kokenis  1.038617
7                Baylor O. Sims  1.007709
8          Stanford N. Ogwumike  0.993488
9          Tennessee G. Johnson  0.982507
10  Notre Dame S. Diggins-Smith  0.962101
11        Notre Dame B. Mallory  0.962101
12         Notre Dame D. Peters  0.962101
13        Notre Dame N. Novosel  0.962101
14   St. John's (NY) D. Stevens  0.959929
15             Baylor J. Madden  0.949321
16         Connecticut K. Faris  0.916773
17        Connecticut S. Dolson  0.916773
18         Connecticut T. Hayes  0.916773
19       Connecticut B. Hartley  0.916773
20           Baylor D. Williams  0.876722
21           Tennessee V. Baugh  0.847231
22             Duke E. Williams  0.847026
23                 Duke C. Gray  0.847026
24               Duke H. Peters  0.847026
25       Tennessee S. Stricklen  0.846725

### Miscellaneous

##### Save Rankings

Get last available lineup for each team

In [8]:
starter_to_rating = dict(zip(df_ratings_display['Starter'], df_ratings_display['Rating']))

len(starter_to_rating)

3030

In [9]:
df_last_starters = (
    df
    .sort_values(by=['Date']).groupby(['Team'])
    .tail(1)
    .reset_index(drop=True)[['Team'] + [f'Team Starter {i}' for i in range(1, 6)]]
)

df_last_starters

,Team,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5
0,New Orleans,New Orleans K. Chaney,New Orleans S. Drake,New Orleans M. Sipos,New Orleans K. Thomas,New Orleans T. Wallace
1,Southeast Missouri State,Southeast Missouri State B. Beck,Southeast Missouri State K. Evans,Southeast Missouri State B. Harriel,Southeast Missouri State B. Roberts,Southeast Missouri State C. Shiffer
2,Rhode Island,Rhode Island E. Cloutier,Rhode Island C. Lehnertz,Rhode Island S. Session,Rhode Island S. Turpin,Rhode Island T. Whittaker
3,Jacksonville State,Jacksonville State D. Lane,Jacksonville State B. Manning,Jacksonville State A. McCarthy,Jacksonville State B. Morrow,Jacksonville State D. Vaughn
4,Lipscomb,Lipscomb A. Bowers,Lipscomb B. Duerk,Lipscomb M. Faulkner,Lipscomb L. McAlister,Lipscomb S. Robinson
...,...,...,...,...,...,...
334,Charleston Southern,Charleston Southern L. Alston,Charleston Southern E. Bratcher,Charleston Southern R. Coward,Charleston Southern S. Jones,Charleston Southern K. Rutledge
335,Cincinnati,Cincinnati C. Chisholm,Cincinnati K. Cook,Cincinnati D. Hollins,Cincinnati J. Randolph,Cincinnati B. Reaves
336,Central Arkansas,Central Arkansas C. Duever,Central Arkansas N. Guiden,Central Arkansas M. Herbert,Central Arkansas M. Rice,Central Arkansas D. Rogers
337,Pacific,Pacific G. Johnson,Pacific K. Kenyon,Pacific E. McKenzie,Pacific S. Pettinger,Pacific K. Rodriguez
338,San Diego,San Diego I. Chilcot,San Diego D. Conners,San Diego A. Kame,San Diego F. Wijenberg,San Diego M. Woodrow

In [10]:
for i in range(1, 6):
    df_last_starters[f'Team Starter {i} Rating'] = df_last_starters[f'Team Starter {i}'].map(starter_to_rating)

df_last_starters['Rating'] = df_last_starters[[f'Team Starter {i} Rating' for i in range(1, 6)]].mean(axis=1)

df_last_starters

,Team,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5,Team Starter 1 Rating,Team Starter 2 Rating,Team Starter 3 Rating,Team Starter 4 Rating,Team Starter 5 Rating,Rating
0,New Orleans,New Orleans K. Chaney,New Orleans S. Drake,New Orleans M. Sipos,New Orleans K. Thomas,New Orleans T. Wallace,-0.310830,-0.310830,-0.310830,-0.310830,-0.310830,-0.310830
1,Southeast Missouri State,Southeast Missouri State B. Beck,Southeast Missouri State K. Evans,Southeast Missouri State B. Harriel,Southeast Missouri State B. Roberts,Southeast Missouri State C. Shiffer,-0.429688,-0.312074,-0.397635,-0.429688,-0.384244,-0.390666
2,Rhode Island,Rhode Island E. Cloutier,Rhode Island C. Lehnertz,Rhode Island S. Session,Rhode Island S. Turpin,Rhode Island T. Whittaker,-0.655953,-0.656295,-0.655953,-0.006575,-0.295557,-0.454067
3,Jacksonville State,Jacksonville State D. Lane,Jacksonville State B. Manning,Jacksonville State A. McCarthy,Jacksonville State B. Morrow,Jacksonville State D. Vaughn,-0.695612,-0.750166,-0.201263,-0.593636,-0.750166,-0.598169
4,Lipscomb,Lipscomb A. Bowers,Lipscomb B. Duerk,Lipscomb M. Faulkner,Lipscomb L. McAlister,Lipscomb S. Robinson,-0.509276,-0.466562,-0.509276,0.300335,-0.003768,-0.237710
...,...,...,...,...,...,...,...,...,...,...,...,...
334,Charleston Southern,Charleston Southern L. Alston,Charleston Southern E. Bratcher,Charleston Southern R. Coward,Charleston Southern S. Jones,Charleston Southern K. Rutledge,-0.121982,0.118054,-0.121982,-0.165291,-0.176547,-0.093550
335,Cincinnati,Cincinnati C. Chisholm,Cincinnati K. Cook,Cincinnati D. Hollins,Cincinnati J. Randolph,Cincinnati B. Reaves,0.174565,0.174565,0.281353,0.006646,0.230296,0.173485
336,Central Arkansas,Central Arkansas C. Duever,Central Arkansas N. Guiden,Central Arkansas M. Herbert,Central Arkansas M. Rice,Central Arkansas D. Rogers,-0.298941,0.042261,0.042261,0.180800,0.383463,0.069969
337,Pacific,Pacific G. Johnson,Pacific K. Kenyon,Pacific E. McKenzie,Pacific S. Pettinger,Pacific K. Rodriguez,-0.021458,0.002415,0.217108,0.152717,0.217108,0.113578
338,San Diego,San Diego I. Chilcot,San Diego D. Conners,San Diego A. Kame,San Diego F. Wijenberg,San Diego M. Woodrow,0.367643,0.394949,0.348421,0.508103,0.394949,0.402813

In [11]:
df_sheet = df_last_starters[['Team', 'Rating']].copy().sort_values(by=['Rating'], ascending=False, ignore_index=True)

df_sheet.head(25)

                  Team    Rating
0               Baylor  1.036960
1           Notre Dame  0.914834
2          Connecticut  0.900011
3             Stanford  0.884266
4             Delaware  0.796963
5            Tennessee  0.732267
6             Maryland  0.717093
7            Green Bay  0.665692
8      St. Bonaventure  0.637536
9                 Duke  0.613300
10             Rutgers  0.576134
11          California  0.571924
12     St. John's (NY)  0.563911
13        Georgia Tech  0.562934
14              Dayton  0.557009
15          Penn State  0.556792
16          Miami (FL)  0.538421
17  Florida Gulf Coast  0.525559
18             Gonzaga  0.523542
19          Georgetown  0.523143
20           Princeton  0.520244
21             Georgia  0.501853
22       West Virginia  0.491942
23           Texas A&M  0.491685
24       Brigham Young  0.491684

In [12]:
df_sheet.to_parquet(f'../data/preprocessed/womens_starters/starters_{season}.parquet')

'Done'

'Done'